name = "HardySpace_formalization"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HardySpaceFormalization"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "b4384330e5b9d7268e11d3136e669205994fa74a"

[[lean_lib]]
name = "HardySpaceFormalization"
