import Mathlib.MeasureTheory.Function.LpSeminorm.Defs
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.MeasureTheory.Measure.OpenPos
import Mathlib.MeasureTheory.Measure.Support

open Set Filter
open scoped ENNReal

namespace MeasureTheory

noncomputable section

variable {α E : Type*} [MeasurableSpace α] [NormedAddCommGroup E] {μ : Measure α}

-- # This file is generated by codex without review!

lemma essSup_eq_iSup_of_forall_lt_measure_ne_zero
    {μ : Measure α} {f : α → ℝ≥0∞}
    (h : ∀ a, a < (⨆ x, f x) → μ {x | a < f x} ≠ 0) :
    essSup f μ = ⨆ x, f x := by
  apply le_antisymm
  · refine essSup_le_of_ae_le (⨆ x, f x) ?_
    exact Eventually.of_forall fun x => le_iSup (fun y => f y) x
  · rw [essSup_eq_sInf]
    refine le_sInf ?_
    intro a ha
    by_contra hle
    exact (h a (lt_of_not_ge hle)) (by simpa using ha)

lemma essSup_enorm_eq_iSup_enorm_of_continuous_of_isOpenPosMeasure
  {μ : Measure α} [TopologicalSpace α] [μ.IsOpenPosMeasure] {f : α → E} (hf : Continuous f) :
    essSup (fun x => ‖f x‖ₑ) μ = ⨆ x, ‖f x‖ₑ := by
  apply essSup_eq_iSup_of_forall_lt_measure_ne_zero
  intro a ha
  rw [ne_eq]
  intro hzero
  have hcont : Continuous fun x => ‖f x‖ₑ :=
    continuous_enorm.comp hf
  have hopen : IsOpen {x | a < ‖f x‖ₑ} :=
    isOpen_lt continuous_const hcont
  have hnonempty : ({x | a < ‖f x‖ₑ} : Set α).Nonempty := by
    rcases (lt_iSup_iff.mp ha) with ⟨x, hx⟩
    exact ⟨x, hx⟩
  have hpos : 0 < μ {x | a < ‖f x‖ₑ} :=
    hopen.measure_pos μ hnonempty
  exact (ne_of_gt hpos) hzero

lemma eLpNorm_top_eq_iSup_enorm_of_continuous_of_isOpenPosMeasure
    [TopologicalSpace α] [μ.IsOpenPosMeasure] {f : α → E} (hf : Continuous f) :
    eLpNorm f ∞ μ = ⨆ x, ‖f x‖ₑ := by
  rw [eLpNorm_exponent_top, eLpNormEssSup_eq_essSup_enorm]
  exact essSup_enorm_eq_iSup_enorm_of_continuous_of_isOpenPosMeasure hf

lemma essSup_restrict_eq_iSup_of_continuous_of_support
    [TopologicalSpace α] [OpensMeasurableSpace α] {s : Set α} {φ : α → ℝ≥0∞}
    (hs : NullMeasurableSet s μ) (hφ : Continuous φ)
    (hsupp : s ⊆ (μ.restrict s).support) :
    essSup φ (μ.restrict s) = ⨆ x ∈ s, φ x := by
  apply le_antisymm
  · refine essSup_le_of_ae_le (⨆ x : α, ⨆ (_ : x ∈ s), φ x) ?_
    filter_upwards [ae_restrict_mem₀ (s := s) (μ := μ) hs] with x hx
    exact (le_iSup (fun hx : x ∈ s => φ x) hx).trans
      (le_iSup (fun x : α => ⨆ (_ : x ∈ s), φ x) x)
  · refine iSup_le ?_
    intro x
    refine iSup_le ?_
    intro hx
    by_contra hle
    have hlt : essSup φ (μ.restrict s) < φ x := lt_of_not_ge hle
    have hopen : IsOpen {y | essSup φ (μ.restrict s) < φ y} :=
      isOpen_lt continuous_const hφ
    have hpos : 0 < (μ.restrict s) {y | essSup φ (μ.restrict s) < φ y} := by
      exact (Measure.mem_support_iff_forall (μ := μ.restrict s) x).1
        (hsupp hx) {y | essSup φ (μ.restrict s) < φ y} (hopen.mem_nhds hlt)
    exact (ne_of_gt hpos) (meas_essSup_lt (μ := μ.restrict s) (f := φ))

lemma essSup_restrict_Ico_eq_iSup_of_continuous
    {a b : ℝ} {φ : ℝ → ℝ≥0∞} (hφ : Continuous φ) :
    essSup φ (volume.restrict (Ico a b)) = ⨆ x ∈ Ico a b, φ x := by
  refine essSup_restrict_eq_iSup_of_continuous_of_support
    measurableSet_Ico.nullMeasurableSet hφ ?_
  have hclosed : IsClosed (volume.restrict (Ico a b)).support :=
    Measure.isClosed_support
  refine (Ico_subset_closure_interior a b).trans ?_
  refine hclosed.closure_subset_iff.mpr ?_
  intro x hx
  exact Measure.interior_inter_support (μ := volume) (s := Ico a b)
    ⟨hx, by simp [Measure.support_eq_univ]⟩

end

end MeasureTheory
