import HardySpaceFormalization.eLpNormFixed
import HardySpaceFormalization.essSup_lemma
import Mathlib.Analysis.Complex.Poisson
import Mathlib.LinearAlgebra.Complex.FiniteDimensional
import Mathlib.MeasureTheory.Function.LpSeminorm.LpNorm




/-!
# Classical Hardy space `H^p` on unit disc in ℂ


-/


noncomputable section

open scoped Real ENNReal NNReal
open MeasureTheory Real Complex Set Metric


variable {E : Type*} [NormedAddCommGroup E]

/-- The open unit disc in `ℂ`, represented as the metric ball of radius `1` around `0`. -/
def unitDisc : Set ℂ :=
  Metric.ball (0 : ℂ) 1

lemma radial_point_mem_unitDisc {r θ : ℝ} (hr0 : 0 < r) (hr1 : r < 1) :
    r * exp (I * θ) ∈ unitDisc := by
  rw [unitDisc, Metric.mem_ball, dist_zero_right]
  simp; rw [abs_of_nonneg hr0.le]; assumption

lemma exists_radial_repr_of_mem_unitDisc_ne_zero
    {z : ℂ} (hz : z ∈ unitDisc) (hz0 : z ≠ 0) :
    ∃ r : ℝ, ∃ θ : ℝ, 0 < r ∧ r < 1 ∧ θ ∈ Ico 0 (2 * π) ∧
     z = r * exp (I * θ) := by
  -- This part is given by codex without review
  refine ⟨‖z‖, if 0 ≤ z.arg then z.arg else z.arg + 2 * π, ?_⟩
  have hr0 : 0 < ‖z‖ := norm_pos_iff.mpr hz0
  have hr1 : ‖z‖ < 1 := by simpa [unitDisc, Metric.mem_ball, dist_zero_right] using hz
  refine ⟨hr0, hr1, ?_, ?_⟩
  · by_cases harg : 0 ≤ z.arg
    · simp only [harg, ↓reduceIte, mem_Ico]
      constructor
      · trivial
      · nlinarith [Complex.arg_le_pi z, Real.pi_pos]
    · have harg_lt : z.arg < 0 := lt_of_not_ge harg
      simp only [harg, ↓reduceIte, mem_Ico]
      constructor
      · nlinarith [Complex.neg_pi_lt_arg z, Real.pi_pos]
      · nlinarith [harg_lt]
  · by_cases harg : 0 ≤ z.arg
    · simp [harg]
      simpa [mul_comm] using (Complex.norm_mul_exp_arg_mul_I z).symm
    · simp [harg]
      have hexp : exp (z.arg * I) = exp (I * (z.arg + 2 * π)) := by
        rw [Complex.exp_eq_exp_iff_exists_int]
        use -1; ring
      rw [← hexp]
      exact (Complex.norm_mul_exp_arg_mul_I z).symm

-- # Here are some properties of radial function:

lemma radial_cont {f : ℂ → E} (hf : ContinuousOn f unitDisc)
  {r : ℝ} (hr : 0 < r ∧ r < 1) : Continuous (fun θ : ℝ => f (r * exp (I * θ))) := by
    refine hf.comp_continuous ?_ ?_
    · fun_prop
    · intro θ; exact radial_point_mem_unitDisc hr.1 hr.2

lemma radial_aestronglyMeasurable {f : ℂ → E} (hf : ContinuousOn f unitDisc)
    {r : ℝ} (hr : 0 < r ∧ r < 1) (μ : Measure ℝ) :
    AEStronglyMeasurable (fun θ : ℝ => f (r * exp (I * θ))) μ := by
  exact (radial_cont hf hr).aestronglyMeasurable

namespace HardySpace

-- # Here's the definition of Hardy `p`-norm:

/-- The Hardy `p`-norm on the unit disc. -/
def hardyNorm (f : ℂ → E) (p : ℝ≥0∞) : ℝ≥0∞ :=
   ⨆ (r : ℝ) (_ : 0 < r ∧ r < 1),
    eLpNormFixed (fun (θ : ℝ) ↦ f (r * exp (I * θ))) p
   (ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π)))

lemma hardyNorm_radial_le (f : ℂ → E) (p : ℝ≥0∞) {r : ℝ} (hr : 0 < r ∧ r < 1) :
    eLpNormFixed (fun θ : ℝ => f (r * exp (I * θ))) p
      (ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π)))
      ≤ hardyNorm f p := by
  unfold hardyNorm
  exact (le_iSup (fun hr : 0 < r ∧ r < 1 => eLpNormFixed _ p _) hr).trans
    (le_iSup (fun r : ℝ => ⨆ (_ : 0 < r ∧ r < 1), eLpNormFixed _ p _) r)

lemma circle_measure_isProbabilityMeasure : IsProbabilityMeasure
(ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))) := by
  -- generated by codex with review
  rw [isProbabilityMeasure_iff]
  rw [Measure.smul_apply, Measure.restrict_apply_univ, Real.volume_Ico]
  simp only [smul_eq_mul]
  rw [← ENNReal.ofReal_mul (by positivity)]
  have hreal : 1 / (2 * π) * (2 * π - 0) = 1 := by
    field_simp [Real.pi_ne_zero]; ring
  rw [hreal, ENNReal.ofReal_one]

-- # Here are some properties of Hardy `p`-norm:

/-- Hardy `∞`-norm on the unit disc is equal to the supremum norm on the unit disc. -/
lemma hardyNorm_top_eq_Sup_norm {f : ℂ → E} (hf : ContinuousOn f unitDisc) :
    hardyNorm f ∞ = ⨆ z : unitDisc, ‖f z.1‖ₑ := by
    -- generated by codex with review
    let μ : Measure ℝ := ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))
    have Sup_norm_eq_punctured : ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ
      = ⨆ z : unitDisc, ‖f z.1‖ₑ := by
      let φ : ℂ → ℝ≥0∞ := fun z => ‖f z‖ₑ
      let punctured : Set ℂ := {z | z ∈ unitDisc ∧ z ≠ 0}
      have hunit_open : IsOpen unitDisc := Metric.isOpen_ball
      have hpunctured_open : IsOpen punctured := hunit_open.inter isOpen_ne
      have hφ_unit : ContinuousOn φ unitDisc := by fun_prop
      have hφ_punctured : ContinuousOn φ punctured := hφ_unit.mono (fun _ hz => hz.1)
      have hsupp_unit : unitDisc ⊆ ((volume : Measure ℂ).restrict unitDisc).support := by
        intro z hz
        apply Measure.interior_inter_support (μ := (volume : Measure ℂ)) (s := unitDisc)
        constructor
        . simpa [hunit_open.interior_eq] using hz
        . simp [Measure.support_eq_univ]
      have hrestrict :
          (volume : Measure ℂ).restrict unitDisc = (volume : Measure ℂ).restrict punctured := by
        refine Measure.restrict_congr_set ?_
        filter_upwards [Measure.ae_ne (volume : Measure ℂ) (0 : ℂ)] with z hz0
        exact propext ⟨fun hz => ⟨hz, hz0⟩, fun hz => hz.1⟩
      have hsupp_punctured :
          punctured ⊆ ((volume : Measure ℂ).restrict punctured).support := by
        simpa [hrestrict] using (Subset.trans (fun z hz => hz.1) hsupp_unit)
      have hess_unit : essSup φ ((volume : Measure ℂ).restrict unitDisc)
          = ⨆ z : ℂ, ⨆ (_ : z ∈ unitDisc), φ z :=
        essSup_restrict_eq_iSup_of_continuousOn_of_isOpen hunit_open hφ_unit hsupp_unit
      have hess_punctured : essSup φ ((volume : Measure ℂ).restrict punctured)
          = ⨆ z : ℂ, ⨆ (_ : z ∈ punctured), φ z :=
        essSup_restrict_eq_iSup_of_continuousOn_of_isOpen hpunctured_open hφ_punctured
          hsupp_punctured
      change (⨆ z : punctured, φ z.1) = ⨆ z : unitDisc, ‖f z.1‖ₑ
      rw [iSup_subtype'' punctured φ, ← hess_punctured, ← hrestrict, hess_unit,
        ← iSup_subtype'' unitDisc φ]
    have hardyNorm_top_eq_Sup_norm_punctured :
     hardyNorm f ∞ = ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ := by
     unfold hardyNorm
     simp [eLpNormFixed, eLpNormEssSup]
     have : ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ =
      ⨆ (r : ℝ), ⨆ (_ : 0 < r ∧ r < 1),
      ⨆ (θ : ℝ), ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ := by
        apply le_antisymm
        · apply iSup_le
          intro z
          rcases exists_radial_repr_of_mem_unitDisc_ne_zero z.2.1 z.2.2 with
            ⟨r, θ, hr0, hr1, hθ, hz_repr⟩
          rw [hz_repr]
          grw [le_iSup (fun hθ : θ ∈ Ico 0 (2 * π) => ‖f (r * exp (I * θ))‖ₑ) hθ]
          grw [le_iSup (fun θ : ℝ => ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ) θ]
          grw [le_iSup (fun hr : 0 < r ∧ r < 1 => ⨆ (θ : ℝ),
                ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ) ⟨hr0, hr1⟩]
          exact le_iSup (fun r : ℝ => ⨆ (_ : 0 < r ∧ r < 1), ⨆ (θ : ℝ),
                  ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ) r
        · apply iSup_le; intro r
          apply iSup_le; intro hr
          apply iSup_le; intro θ
          apply iSup_le; intro hθ
          let z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0} := by
            refine ⟨r * exp (I * θ), radial_point_mem_unitDisc hr.1 hr.2, ?_⟩
            refine mul_ne_zero ?_ (exp_ne_zero _)
            exact_mod_cast (ne_of_gt hr.1)
          exact le_iSup (fun z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0} => ‖f z.1‖ₑ) z
     rw [this]; congr; ext r; congr; ext hr
     rw [essSup_ennreal_smul_measure]
     · exact essSup_restrict_Ico_eq_iSup_of_continuous
          (continuous_enorm.comp (radial_cont hf hr))
     · exact ne_of_gt (ENNReal.ofReal_pos.mpr (by positivity))
    rw [hardyNorm_top_eq_Sup_norm_punctured, Sup_norm_eq_punctured]



variable [NormedSpace ℂ E]


lemma hardyNorm_const_smul (c : ℂ) (f : ℂ → E) (p : ℝ≥0∞):
    hardyNorm (c • f) p = eLpFixedScalar c p * hardyNorm f p := by
  simp [hardyNorm, ENNReal.mul_iSup]
  congr; ext r; congr; ext hr
  simpa [Pi.smul_apply] using
    eLpNormFixed_const_smul c (fun θ : ℝ => f (r * exp (I * θ))) p
      (ENNReal.ofReal (π⁻¹ * 2⁻¹) • volume.restrict (Ico 0 (2 * π)))

/-- Hardy norm satisfies triangle inequality. -/
lemma hardyNorm_add_le {p : ℝ≥0∞} {f g : ℂ → E}
    (hf_an : AnalyticOn ℂ f unitDisc) (hg_an : AnalyticOn ℂ g unitDisc) :
    hardyNorm (f + g) p ≤ hardyNorm f p + hardyNorm g p := by
  unfold hardyNorm
  -- This part is given by codex with review
  let μ : Measure ℝ := ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))
  refine iSup_le ?_
  intro r
  refine iSup_le ?_
  intro hr
  have hf_meas : AEStronglyMeasurable (fun θ : ℝ => f (r * exp (I * θ))) μ :=
    radial_aestronglyMeasurable hf_an.continuousOn hr μ
  have hg_meas : AEStronglyMeasurable (fun θ : ℝ => g (r * exp (I * θ))) μ :=
    radial_aestronglyMeasurable hg_an.continuousOn hr μ
  apply (eLpNormFixed_add_le hf_meas hg_meas).trans
  exact add_le_add (hardyNorm_radial_le f p hr) (hardyNorm_radial_le g p hr)


/-- Hardy norm is monotone in the exponent. -/
lemma hardyNorm_le_hardyNorm_of_exponent_le {p q : ℝ≥0∞} {f : ℂ → E}
    (hf_an : AnalyticOn ℂ f unitDisc) (hpq : p ≤ q) [Fact (1 ≤ p)] :
    hardyNorm f p ≤ hardyNorm f q := by
  -- generated by codex with review
  unfold hardyNorm
  let μ : Measure ℝ := ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))
  haveI : IsProbabilityMeasure μ := circle_measure_isProbabilityMeasure
  refine iSup_le ?_
  intro r
  refine iSup_le ?_
  intro hr
  grw [eLpNormFixed_le_eLpNormFixed_of_exponent_le hpq
    (radial_aestronglyMeasurable hf_an.continuousOn hr μ)]
  exact hardyNorm_radial_le f q hr


-- # We define Hardy space on unit disc together with its structure of ℂ-vector space.

/-- Membership in the Hardy space `H^p` on the unit disc. -/
def MemHpDisc (p : ℝ≥0∞) (f : ℂ → E) : Prop :=
  AnalyticOn ℂ f unitDisc ∧ hardyNorm f p < ∞ ∧ ∀ z ∉ unitDisc, f z = 0

/-- Addition of two elements of Hardy space still lies in Hardy space. -/
lemma MemHpDisc.add {p : ℝ≥0∞} {f g : ℂ → E}
    (hf : MemHpDisc (E := E) p f) (hg : MemHpDisc (E := E) p g) :
    MemHpDisc (E := E) p (f + g) := by
    unfold MemHpDisc at *
    rcases hf with ⟨hf_an, ⟨hf_norm, hf_zero⟩⟩
    rcases hg with ⟨hg_an, ⟨hg_norm, hg_zero⟩⟩
    constructor
    . exact AnalyticOn.add hf_an hg_an
    . constructor
      . exact lt_of_le_of_lt (hardyNorm_add_le hf_an hg_an)
          (ENNReal.add_lt_top.2 ⟨hf_norm, hg_norm⟩)
      . intro z hz; simp [Pi.add_apply, hf_zero z hz, hg_zero z hz]

/-- Zero function is an element of Hardy space. -/
lemma MemHpDisc.zero {p : ℝ≥0∞} :
    MemHpDisc (E := E) p (0 : ℂ → E) := by
    unfold MemHpDisc
    constructor
    . exact analyticOn_const
    . constructor
      . unfold hardyNorm
        by_cases hp : p ∈ Ioo (0 : ℝ≥0∞) 1
        · have hpt : 0 < p.toReal := ENNReal.toReal_pos hp.1.ne' (ne_of_lt (hp.2.trans ENNReal.one_lt_top))
          simp [eLpNormFixed, hp, ENNReal.zero_rpow_of_pos hpt]
        · simp [eLpNormFixed, hp]
      . intro z hz; rfl

/-- An element of Hardy space multiplied by a scalar still lies in Hardy space. -/
lemma MemHpDisc.smul {p : ℝ≥0∞} (c : ℂ) {f : ℂ → E}
    (hf : MemHpDisc (E := E) p f) : MemHpDisc (E := E) p (c • f) := by
    unfold MemHpDisc at *
    rcases hf with ⟨hf_an, ⟨hf_norm, hf_zero⟩⟩
    constructor
    . exact AnalyticOn.const_smul hf_an
    . constructor
      . rw [hardyNorm_const_smul]
        have hscalar : eLpFixedScalar c p < ∞ := by
          by_cases hp : p ∈ Ioo (0 : ℝ≥0∞) 1
          · simp [eLpFixedScalar, hp]
            exact ENNReal.rpow_lt_top_of_nonneg ENNReal.toReal_nonneg (by simp)
          · simp [eLpFixedScalar, hp]
        exact ENNReal.mul_lt_top hscalar hf_norm
      . intro z hz; simp [hf_zero z hz]

/-- Classical definition of Hardy space on unit disc as ℂ-vector space. -/
def HpDisc (p : ℝ≥0∞) : Submodule ℂ (ℂ → E) where
  carrier := {f : ℂ → E | MemHpDisc (E := E) p f}
  add_mem' := MemHpDisc.add
  zero_mem' := MemHpDisc.zero
  smul_mem' := MemHpDisc.smul

/-- Monotonicity of Hardy spaces on the unit disc: `H^q ⊆ H^p` for `1 ≤ p ≤ q`. -/
theorem HpDisc_mono {p q : ℝ≥0∞} (hpq : p ≤ q) [Fact (1 ≤ p)] :
    HpDisc (E := E) q ≤ HpDisc (E := E) p := by
  intro f hf
  simp [HpDisc] at *
  rcases hf with ⟨hf_an, hf_norm, hf_zero⟩
  constructor
  · exact hf_an
  · constructor
    · exact lt_of_le_of_lt (hardyNorm_le_hardyNorm_of_exponent_le hf_an hpq) hf_norm
    · exact hf_zero

-- # Note: monotonicity of Hardy spaces also holds for `0 < p ≤ q`, but for simplicity we ask for `1≤ p`.

end HardySpace
end
