import HardySpaceFormalization.HardySpaceFirstDefs
import Mathlib.Analysis.Analytic.Basic
import Mathlib.Analysis.InnerProductSpace.Harmonic.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real

-- ## Remark: This file is mostly generated by Codex, an AI-agent developed by Openai.

/-!
# Generalized Hardy space `H^p(Ω)` on general domain in ℂ^n

-/

noncomputable section

open scoped ENNReal
namespace HardySpace

/--
A real-valued scalar function has a harmonic majorant on `Ω` if it is bounded above on `Ω`
by a real-valued function that is harmonic in a neighborhood of `Ω`.
-/
def HasHarmonicMajorant
    {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]
    (Ω : Set V) (g : V → ℝ) : Prop :=
  ∃ u : V → ℝ, InnerProductSpace.HarmonicOnNhd u Ω ∧ ∀ z ∈ Ω, g z ≤ u z

/--
Membership in generalized `p`-Hardy class on an unbundled domain `Ω`.

The function is required to be analytic on `Ω`, and `z ↦ ‖f z‖^p` must admit a harmonic
majorant there.
-/
def MemHp
    {V E : Type*}
    [NormedAddCommGroup V] [NormedSpace ℂ V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]
    [NormedAddCommGroup E] [NormedSpace ℂ E] [CompleteSpace E]
    (Ω : Set V) (p : ℝ≥0∞) (f : V → E) : Prop :=
  0 < p ∧
    AnalyticOn ℂ f Ω ∧
    match p with
    | ∞ =>
        ∃ C : ℝ, 0 ≤ C ∧ ∀ z ∈ Ω, ‖f z‖ ≤ C
    | _ =>
        HasHarmonicMajorant Ω (fun z => Real.rpow ‖f z‖ (ENNReal.toReal p))


-- ## Equivalence between `MemHp` and `MemHpDisc` over unit disc

lemma radialPoint_mem_unitDisc {r θ : ℝ} (hr0 : 0 < r) (hr1 : r < 1) :
    radialPoint r θ ∈ unitDisc := by
  rw [unitDisc, Metric.mem_ball, dist_zero_right]
  calc
    ‖radialPoint r θ‖ = |r| := by
      simp [radialPoint, Complex.norm_exp_ofReal_mul_I]
    _ = r := abs_of_nonneg hr0.le
    _ < 1 := hr1

/-- The `p = ∞` case of the equivalence between hardy space definitions over unit disc. -/
lemma memHpDisc_iff_memHp_onDisc_top
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E] [CompleteSpace E]
    {f : ℂ → E} :
    MemHpDisc ∞ f ↔ MemHp unitDisc ∞ f := by
  constructor
  · intro hdisc
    rcases hdisc with ⟨han, hfin⟩
    refine ⟨by simp, han, ENNReal.toReal (hardyNorm f ∞), ENNReal.toReal_nonneg, ?_⟩
    intro z hz
    have hpoint : ENNReal.ofReal ‖f z‖ ≤ hardyNorm f ∞ := by
      unfold hardyNorm
      simp only [ENNReal.top_ne_zero, ↓reduceIte]
      change ENNReal.ofReal ‖f z‖ ≤
        ⨆ (w : ℂ) (_ : w ∈ unitDisc), ENNReal.ofReal ‖f w‖
      exact le_iSup₂_of_le z hz le_rfl
    exact (ENNReal.ofReal_le_iff_le_toReal (ne_of_lt hfin)).mp hpoint
  · intro hmaj
    rcases hmaj with ⟨_hpos, han, C, _hC0, hC⟩
    refine ⟨han, ?_⟩
    suffices hardyNorm f ∞ ≤ ENNReal.ofReal C from this.trans_lt ENNReal.ofReal_lt_top
    unfold hardyNorm
    simp only [ENNReal.top_ne_zero, ↓reduceIte]
    apply iSup_le
    intro z
    apply iSup_le
    intro hz
    exact ENNReal.ofReal_le_ofReal (hC z hz)

/-- The finite-exponent case of the equivalence between hardy space definitions over disc. -/
lemma memHpDisc_iff_memHp_onDisc_of_ne_top
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E] [CompleteSpace E]
    {p : ℝ≥0∞} (hp0 : p ≠ 0) (hpTop : p ≠ ∞) {f : ℂ → E} :
    MemHpDisc p f ↔ MemHp unitDisc p f := by
  sorry

/-- The equivalence between the classical and generalized definitions on the unit disc. -/
theorem memHpDisc_iff_memHp_onDisc
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E] [CompleteSpace E]
    {p : ℝ≥0∞} (hp0 : p ≠ 0) {f : ℂ → E} :
    MemHpDisc p f ↔ MemHp unitDisc p f := by
  by_cases hpTop : p = ∞
  · simpa [hpTop] using
      (memHpDisc_iff_memHp_onDisc_top (E := E) (f := f))
  · exact memHpDisc_iff_memHp_onDisc_of_ne_top (E := E) hp0 hpTop (f := f)

end HardySpace
