import HardySpaceFormalization.HardySpaceFirstDefs
import Mathlib.Analysis.Analytic.Basic
import Mathlib.Analysis.InnerProductSpace.Harmonic.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.LinearAlgebra.Complex.FiniteDimensional

-- ## Remark: This file is mostly generated by Codex, an AI-agent developed by Openai.

/-!
# Generalized Hardy space `H^p(Ω)` on general domain in ℂ^n

-/

noncomputable section

open scoped ENNReal
namespace HardySpace

/--
A real-valued scalar function has a harmonic majorant on `Ω` if it is bounded above on `Ω`
by a real-valued function that is harmonic in a neighborhood of `Ω`.
-/
def HasHarmonicMajorant
    {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]
    (Ω : Set V) (g : V → ℝ) : Prop :=
  ∃ u : V → ℝ, InnerProductSpace.HarmonicOnNhd u Ω ∧ ∀ z ∈ Ω, g z ≤ u z

/--
Membership in generalized `p`-Hardy class on an unbundled domain `Ω`.

The function is required to be analytic on `Ω`, and `z ↦ ‖f z‖^p` must admit a harmonic
majorant there.
-/
def MemHp
    {V E : Type*}
    [NormedAddCommGroup V] [NormedSpace ℂ V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]
    [NormedAddCommGroup E] [NormedSpace ℂ E]
    (Ω : Set V) (p : ℝ≥0∞) (f : V → E) : Prop :=
  0 < p ∧ AnalyticOn ℂ f Ω ∧
    match p with
    | ∞ =>
        ∃ C : ℝ, 0 ≤ C ∧ ∀ z ∈ Ω, ‖f z‖ ≤ C
    | _ =>
        HasHarmonicMajorant Ω fun z => ‖f z‖ ^ ENNReal.toReal p


-- ## Equivalence between `MemHp` and `MemHpDisc` over unit disc


/-- The `p = ∞` case of the equivalence between hardy space definitions over unit disc. -/
lemma memHpDisc_iff_memHp_onDisc_top
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
    {f : ℂ → E} :
    MemHpDisc ∞ f ↔ MemHp unitDisc ∞ f := by sorry

/-- The finite-exponent case of the equivalence between hardy space definitions over disc. -/
lemma memHpDisc_iff_memHp_onDisc_of_ne_top
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
    {p : ℝ≥0∞} (hp0 : p ≠ 0) (hpTop : p ≠ ∞) {f : ℂ → E} :
    MemHpDisc p f ↔ MemHp unitDisc p f := by
  sorry

/-- The equivalence between the classical and generalized definitions on the unit disc. -/
theorem memHpDisc_iff_memHp_onDisc
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
    {p : ℝ≥0∞} (hp0 : p ≠ 0) {f : ℂ → E} :
    MemHpDisc p f ↔ MemHp unitDisc p f := by
  by_cases hpTop : p = ∞
  · simpa [hpTop] using
      (memHpDisc_iff_memHp_onDisc_top (E := E) (f := f))
  · exact memHpDisc_iff_memHp_onDisc_of_ne_top (E := E) hp0 hpTop (f := f)

end HardySpace
