import Mathlib.Analysis.Complex.CauchyIntegral
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Data.ENNReal.Real
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Function.LpSeminorm.Defs
import Mathlib.MeasureTheory.Function.LpSeminorm.SMul
import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
import Mathlib.MeasureTheory.Measure.Haar.OfBasis
import Mathlib.LinearAlgebra.Complex.FiniteDimensional
import Mathlib.Analysis.Analytic.Constructions
import HardySpaceFormalization.eLpNormFixed
import HardySpaceFormalization.essSup_lemma



/-!
# Classical Hardy space `H^p` on unit disc in ℂ


-/


noncomputable section

open scoped Real ENNReal
open MeasureTheory Real Complex Set


variable {E : Type*} [NormedAddCommGroup E]

/-- The open unit disc in `ℂ`, represented as the metric ball of radius `1` around `0`. -/
def unitDisc : Set ℂ :=
  Metric.ball (0 : ℂ) 1

lemma radial_point_mem_unitDisc {r θ : ℝ} (hr0 : 0 < r) (hr1 : r < 1) :
    r * exp (I * θ) ∈ unitDisc := by
  rw [unitDisc, Metric.mem_ball, dist_zero_right]
  calc
    ‖r * exp (I * θ)‖ = |r| := by simp
    _ = r := abs_of_nonneg hr0.le
    _ < 1 := hr1

lemma exists_radial_repr_of_mem_unitDisc_ne_zero
    {z : ℂ} (hz : z ∈ unitDisc) (hz0 : z ≠ 0) :
    ∃ r : ℝ, ∃ θ : ℝ,
      0 < r ∧ r < 1 ∧ θ ∈ Ico 0 (2 * π) ∧
      z = r * exp (I * θ) := by
  -- This part is given by codex without review
  refine ⟨‖z‖, if 0 ≤ z.arg then z.arg else z.arg + 2 * π, ?_⟩
  have hr0 : 0 < ‖z‖ := norm_pos_iff.mpr hz0
  have hr1 : ‖z‖ < 1 := by simpa [unitDisc, Metric.mem_ball, dist_zero_right] using hz
  refine ⟨hr0, hr1, ?_, ?_⟩
  · by_cases harg : 0 ≤ z.arg
    · simp only [harg, ↓reduceIte, mem_Ico]
      constructor
      · trivial
      · nlinarith [Complex.arg_le_pi z, Real.pi_pos]
    · have harg_lt : z.arg < 0 := lt_of_not_ge harg
      simp only [harg, ↓reduceIte, mem_Ico]
      constructor
      · nlinarith [Complex.neg_pi_lt_arg z, Real.pi_pos]
      · nlinarith [harg_lt]
  · by_cases harg : 0 ≤ z.arg
    · simp [harg]
      simpa [mul_comm] using (Complex.norm_mul_exp_arg_mul_I z).symm
    · simp [harg]
      have hexp : exp (z.arg * I) = exp (I * (z.arg + 2 * π)) := by
        rw [Complex.exp_eq_exp_iff_exists_int]
        refine ⟨-1, ?_⟩
        ring
      calc
        z = ‖z‖ * exp (z.arg * I) := (Complex.norm_mul_exp_arg_mul_I z).symm
        _ = ‖z‖ * exp (I * (z.arg + 2 * π)) := by rw [hexp]

lemma radial_cont {f : ℂ → E} (hf : ContinuousOn f unitDisc)
  {r : ℝ} (hr : 0 < r ∧ r < 1) : Continuous (fun θ : ℝ => f (r * exp (I * θ))) := by
    refine hf.comp_continuous ?_ ?_
    · fun_prop
    · intro θ; exact radial_point_mem_unitDisc hr.1 hr.2

lemma radial_aestronglyMeasurable {f : ℂ → E} (hf : ContinuousOn f unitDisc)
    {r : ℝ} (hr : 0 < r ∧ r < 1) (μ : Measure ℝ) :
    AEStronglyMeasurable (fun θ : ℝ => f (r * exp (I * θ))) μ := by
  exact (radial_cont hf hr).aestronglyMeasurable

namespace HardySpace

/-- The Hardy `p`-norm on the unit disc. -/
def hardyNorm (f : ℂ → E) (p : ℝ≥0∞) : ℝ≥0∞ :=
   ⨆ (r : ℝ) (_ : 0 < r ∧ r < 1),
    eLpNormFixed (fun (θ : ℝ) ↦ f (r * exp (I * θ))) p
   (ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π)))

/-- Hardy `∞`-norm on the unit disc is equal to the supremum norm on the disc. -/
lemma hardyNorm_top_eq_Sup_norm {f : ℂ → E} (hf : ContinuousOn f unitDisc) :
    hardyNorm f ∞ = ⨆ z : unitDisc, ‖f z.1‖ₑ := by
    let μ : Measure ℝ := ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))
    have Sup_norm_eq_punctured : ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ
      = ⨆ z : unitDisc, ‖f z.1‖ₑ := by
      apply le_antisymm
      · refine iSup_le ?_; intro z
        exact le_iSup (fun z : unitDisc => ‖f z.1‖ₑ) ⟨z.1, z.2.1⟩
      · refine iSup_le ?_; intro z
        by_cases hz0 : z.1 = 0
        · -- This part is generated by codex without review
          rw [hz0]
          let zseq : ℕ → ℂ := fun n => ((1 / (((n + 1 : ℕ) : ℝ) + 1) : ℝ) : ℂ)
          have hzseq_mem : ∀ n, zseq n ∈ unitDisc ∧ zseq n ≠ 0 := by
            intro n
            constructor
            · rw [unitDisc, Metric.mem_ball, dist_zero_right]
              have hden : 0 < ((n + 1 : ℕ) : ℝ) + 1 := by positivity
              have hden_one : (1 : ℝ) < ((n + 1 : ℕ) : ℝ) + 1 := by
                have hn_pos : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by exact_mod_cast Nat.succ_pos n
                linarith
              have hnonneg : 0 ≤ 1 / (((n + 1 : ℕ) : ℝ) + 1) := by positivity
              change ‖((1 / (((n + 1 : ℕ) : ℝ) + 1) : ℝ) : ℂ)‖ < 1
              rw [Complex.norm_of_nonneg hnonneg]
              exact (div_lt_one hden).2 hden_one
            · change ((1 / (((n + 1 : ℕ) : ℝ) + 1) : ℝ) : ℂ) ≠ 0
              have hden : (((n + 1 : ℕ) : ℝ) + 1) ≠ 0 := by positivity
              exact_mod_cast one_div_ne_zero hden
          have hle_seq :
              ∀ n, ‖f (zseq n)‖ₑ ≤
                ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ := by
            intro n
            exact le_iSup
              (fun z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0} => ‖f z.1‖ₑ)
              ⟨zseq n, (hzseq_mem n).1, (hzseq_mem n).2⟩
          have hzseq_tendsto : Filter.Tendsto zseq Filter.atTop (nhds (0 : ℂ)) := by
            have hreal :
                Filter.Tendsto
                  (fun n : ℕ => 1 / (((n + 1 : ℕ) : ℝ) + 1))
                  Filter.atTop (nhds (0 : ℝ)) := by
              convert
                (tendsto_one_div_add_atTop_nhds_zero_nat (𝕜 := ℝ)).comp
                  (Filter.tendsto_add_atTop_nat 1)
                using 1
            exact (Complex.continuous_ofReal.tendsto 0).comp hreal
          have hfseq_tendsto :
              Filter.Tendsto (fun n => ‖f (zseq n)‖ₑ) Filter.atTop (nhds ‖f 0‖ₑ) := by
            have h0_mem : (0 : ℂ) ∈ unitDisc := by simp [unitDisc]
            have hcont0 : ContinuousAt f 0 :=
              hf.continuousAt (Metric.isOpen_ball.mem_nhds h0_mem)
            exact (continuous_enorm.tendsto (f 0)).comp (hcont0.tendsto.comp hzseq_tendsto)
          exact le_of_tendsto' hfseq_tendsto hle_seq
        · exact le_iSup (fun w : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0} => ‖f w.1‖ₑ)
            ⟨z.1, z.2, hz0⟩
    have hardyNorm_top_eq_Sup_norm_punctured :
     hardyNorm f ∞ = ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ := by
     unfold hardyNorm
     simp [eLpNormFixed, eLpNormEssSup]
     have : ⨆ z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0}, ‖f z.1‖ₑ =
      ⨆ (r : ℝ), ⨆ (_ : 0 < r ∧ r < 1),
      ⨆ (θ : ℝ), ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ := by
        apply le_antisymm
        · refine iSup_le ?_
          intro z
          rcases exists_radial_repr_of_mem_unitDisc_ne_zero z.2.1 z.2.2 with
            ⟨r, θ, hr0, hr1, hθ, hz_repr⟩
          rw [hz_repr]
          calc
            ‖f (r * exp (I * θ))‖ₑ
                ≤ ⨆ (_ : θ ∈ Set.Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ :=
              le_iSup (fun hθ : θ ∈ Ico 0 (2 * π) => ‖f (r * exp (I * θ))‖ₑ) hθ
            _ ≤ ⨆ (θ : ℝ), ⨆ (_ : θ ∈ Set.Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ :=
              le_iSup (fun θ : ℝ => ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ) θ
            _ ≤ ⨆ (_ : 0 < r ∧ r < 1), ⨆ (θ : ℝ), ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ :=
              le_iSup (fun hr : 0 < r ∧ r < 1 => ⨆ (θ : ℝ),
                ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ) ⟨hr0, hr1⟩
            _ ≤ ⨆ (r : ℝ), ⨆ (_ : 0 < r ∧ r < 1), ⨆ (θ : ℝ), ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ :=
              le_iSup (fun r : ℝ => ⨆ (_ : 0 < r ∧ r < 1), ⨆ (θ : ℝ),
                  ⨆ (_ : θ ∈ Ico 0 (2 * π)), ‖f (r * exp (I * θ))‖ₑ) r
        · refine iSup_le ?_; intro r
          refine iSup_le ?_; intro hr
          refine iSup_le ?_; intro θ
          refine iSup_le ?_; intro hθ
          let z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0} :=
            ⟨r * exp (I * θ), radial_point_mem_unitDisc hr.1 hr.2, by
              have hr_ne : (r : ℂ) ≠ 0 := by exact_mod_cast (ne_of_gt hr.1)
              exact mul_ne_zero hr_ne (exp_ne_zero _)⟩
          exact le_iSup (fun z : {z : ℂ // z ∈ unitDisc ∧ z ≠ 0} => ‖f z.1‖ₑ) z
     rw [this]; congr; ext r; congr; ext hr
     rw [essSup_ennreal_smul_measure]
     · exact limsup_ae_restrict_Ico_eq_iSup_of_continuous
          (by positivity) (continuous_enorm.comp (radial_cont hf hr))
     · exact ne_of_gt (ENNReal.ofReal_pos.mpr (by positivity))
    rw [hardyNorm_top_eq_Sup_norm_punctured, Sup_norm_eq_punctured]



variable [NormedSpace ℂ E]


lemma hardyNorm_const_smul (c : ℂ) (f : ℂ → E) (p : ℝ≥0∞):
    hardyNorm (c • f) p = eLpFixedScalar c p * hardyNorm f p := by
  simp [hardyNorm, ENNReal.mul_iSup]
  congr
  ext r
  congr
  ext hr
  simpa [Pi.smul_apply] using
    eLpNormFixed_const_smul c (fun θ : ℝ => f (r * exp (I * θ))) p
      (ENNReal.ofReal (π⁻¹ * 2⁻¹) • volume.restrict (Ico 0 (2 * π)))

/-- Hardy norm satisfies triangle inequality. -/
lemma hardyNorm_add_le {p : ℝ≥0∞} {f g : ℂ → E}
    (hf_an : AnalyticOn ℂ f unitDisc) (hg_an : AnalyticOn ℂ g unitDisc) :
    hardyNorm (f + g) p ≤ hardyNorm f p + hardyNorm g p := by
  unfold hardyNorm
  -- This part is given by codex
  let μ : Measure ℝ := ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))
  change
    (⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => _) p μ) ≤
        (⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => _) p μ) +
          (⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => _) p μ)
  refine iSup_le ?_
  intro r
  refine iSup_le ?_
  intro hr
  have hf_meas : AEStronglyMeasurable (fun θ : ℝ => f (r * exp (I * θ))) μ :=
    radial_aestronglyMeasurable hf_an.continuousOn hr μ
  have hg_meas : AEStronglyMeasurable (fun θ : ℝ => g (r * exp (I * θ))) μ :=
    radial_aestronglyMeasurable hg_an.continuousOn hr μ
  calc
    eLpNormFixed (fun θ : ℝ => (f + g) _) p μ
        ≤ eLpNormFixed (fun θ : ℝ => f _) p μ + eLpNormFixed (fun θ : ℝ => g _) p μ := by
         simpa [Pi.add_apply] using eLpNormFixed_add_le hf_meas hg_meas
    _ ≤ (⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => f _) p μ) +
        (⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => g _) p μ) := by
       have hf_le : eLpNormFixed (fun θ : ℝ => f (r * exp (I * θ))) p μ ≤
        ⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => f (r * exp (I * θ))) p μ := by
        exact (le_iSup (fun hr : 0 < r ∧ r < 1 => eLpNormFixed (fun θ : ℝ => f (r * exp (I * θ))) p μ) hr).trans
          (le_iSup (fun r : ℝ => ⨆ (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => f (r * exp (I * θ))) p μ) r)
       have hg_le : eLpNormFixed (fun θ : ℝ => g (r * exp (I * θ))) p μ ≤
        ⨆ (r : ℝ) (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => g (r * exp (I * θ))) p μ := by
         exact (le_iSup (fun hr : 0 < r ∧ r < 1 => eLpNormFixed (fun θ : ℝ => g (r * exp (I * θ))) p μ) hr).trans
          (le_iSup (fun r : ℝ => ⨆ (_ : 0 < r ∧ r < 1), eLpNormFixed (fun θ : ℝ => g (r * exp (I * θ))) p μ) r)
       exact add_le_add hf_le hg_le

/-- Membership in the Hardy space `H^p` on the unit disc. -/
def MemHpDisc
    (p : ℝ≥0∞) (f : ℂ → E) : Prop :=
  AnalyticOn ℂ f unitDisc ∧ hardyNorm f p < ∞ ∧ ∀ z ∉ unitDisc, f z = 0


lemma MemHpDisc.add {p : ℝ≥0∞} {f g : ℂ → E}
    (hf : MemHpDisc (E := E) p f) (hg : MemHpDisc (E := E) p g) :
    MemHpDisc (E := E) p (f + g) := by
    unfold MemHpDisc at *
    rcases hf with ⟨hf_an, ⟨hf_norm, hf_zero⟩⟩
    rcases hg with ⟨hg_an, ⟨hg_norm, hg_zero⟩⟩
    constructor
    . exact AnalyticOn.add hf_an hg_an
    . constructor
      . exact lt_of_le_of_lt (hardyNorm_add_le hf_an hg_an)
          (ENNReal.add_lt_top.2 ⟨hf_norm, hg_norm⟩)
      . intro z hz; simp [Pi.add_apply, hf_zero z hz, hg_zero z hz]

lemma MemHpDisc.zero {p : ℝ≥0∞} :
    MemHpDisc (E := E) p (0 : ℂ → E) := by
    unfold MemHpDisc
    constructor
    . exact analyticOn_const
    . constructor
      . unfold hardyNorm
        by_cases hp : p ∈ Ioo (0 : ℝ≥0∞) 1
        · have hpt : 0 < p.toReal := ENNReal.toReal_pos hp.1.ne' (ne_of_lt (hp.2.trans ENNReal.one_lt_top))
          simp [eLpNormFixed, hp, ENNReal.zero_rpow_of_pos hpt]
        · simp [eLpNormFixed, hp]
      . intro z hz; rfl

lemma MemHpDisc.smul {p : ℝ≥0∞} (c : ℂ) {f : ℂ → E}
    (hf : MemHpDisc (E := E) p f) : MemHpDisc (E := E) p (c • f) := by
    unfold MemHpDisc at *
    rcases hf with ⟨hf_an, ⟨hf_norm, hf_zero⟩⟩
    constructor
    . exact AnalyticOn.const_smul hf_an
    . constructor
      . rw [hardyNorm_const_smul]
        have hscalar : eLpFixedScalar c p < ∞ := by
          by_cases hp : p ∈ Ioo (0 : ℝ≥0∞) 1
          · simp [eLpFixedScalar, hp]
            exact ENNReal.rpow_lt_top_of_nonneg ENNReal.toReal_nonneg (by simp)
          · simp [eLpFixedScalar, hp]
        exact ENNReal.mul_lt_top hscalar hf_norm
      . intro z hz; simp [hf_zero z hz]


def HpDisc (p : ℝ≥0∞) : Submodule ℂ (ℂ → E) where
  carrier := {f : ℂ → E | MemHpDisc (E := E) p f}
  add_mem' := MemHpDisc.add
  zero_mem' := MemHpDisc.zero
  smul_mem' := MemHpDisc.smul

namespace HpDisc

instance instNorm (p : ℝ≥0∞) : Norm (HpDisc (E := E) p) where
  norm f := (hardyNorm (E := E) f.1 p).toReal

instance instDist (p : ℝ≥0∞) : Dist (HpDisc (E := E) p) where
  dist f g := ‖-f + g‖

instance instEDist (p : ℝ≥0∞) : EDist (HpDisc (E := E) p) where
  edist f g := hardyNorm (E := E) (f.1 - g.1) p

@[simp] lemma norm_def (p : ℝ≥0∞) (f : HpDisc (E := E) p) :
    ‖f‖ = (hardyNorm (E := E) f.1 p).toReal := by rfl

@[simp] lemma norm_zero (p : ℝ≥0∞) :
    ‖(0 : HpDisc (E := E) p)‖ = 0 := by
  by_cases hp : p ∈ Ioo (0 : ℝ≥0∞) 1
  · have hpt : 0 < p.toReal := ENNReal.toReal_pos hp.1.ne' (ne_of_lt (hp.2.trans ENNReal.one_lt_top))
    simp [hardyNorm, eLpNormFixed, hp, ENNReal.zero_rpow_of_pos hpt]
  · simp [hardyNorm, eLpNormFixed, hp]

@[simp] lemma norm_neg (p : ℝ≥0∞) (f : HpDisc (E := E) p) :
    ‖-f‖ = ‖f‖ := by
  simp [hardyNorm]
  congr; ext r; congr; ext hr
  exact eLpNormFixed_neg (fun θ : ℝ => f.1 (r * exp (I * θ))) p
    (ENNReal.ofReal (π⁻¹ * 2⁻¹) • volume.restrict (Ico 0 (2 * π)))

lemma norm_add_le (p : ℝ≥0∞) (f g : HpDisc (E := E) p) :
    ‖f + g‖ ≤ ‖f‖ + ‖g‖ := by
  rcases f.2 with ⟨hf_an, ⟨hf_norm, _⟩⟩
  rcases g.2 with ⟨hg_an, ⟨hg_norm, _⟩⟩
  simp [norm_def]; exact ENNReal.toReal_le_add (hardyNorm_add_le hf_an hg_an) hf_norm.ne hg_norm.ne


lemma norm_eq_zero_iff (p : ℝ≥0∞)
    {f : HpDisc (E := E) p} [Fact (1 ≤ p)] : ‖f‖ = 0 ↔ f = 0 := by
  constructor
  . intro h; simp [norm_def] at h
    -- This part is given by codex without review
    have hp_ne_zero : p ≠ 0 := ne_of_gt (lt_of_lt_of_le zero_lt_one (Fact.out))
    have hpunctured : ∀ z ∈ unitDisc, z ≠ 0 → f.1 z = 0 := by
      intro z hz hz0
      rcases exists_radial_repr_of_mem_unitDisc_ne_zero hz hz0 with
        ⟨r, θ, hr0, hr1, hθ, hz_repr⟩
      let μ : Measure ℝ := ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Ico 0 (2 * π))
      have hradial_zero : eLpNormFixed (fun θ : ℝ => f.1 (r * exp (I * θ))) p μ = 0 := by
        have hHardy : hardyNorm f.1 p = 0 := by
          rcases (ENNReal.toReal_eq_zero_iff (hardyNorm f.1 p)).1 h with hzero | htop
          · exact hzero
          · exfalso; exact (ne_of_lt f.2.2.1) htop
        have hle : eLpNormFixed (fun θ : ℝ => f.1 (r * exp (I * θ))) p μ ≤ hardyNorm f.1 p := by
          unfold hardyNorm
          exact (le_iSup (fun hr : 0 < r ∧ r < 1 => eLpNormFixed
          (fun θ : ℝ => f.1 (r * exp (I * θ))) p μ) ⟨hr0, hr1⟩).trans
           (le_iSup (fun r : ℝ => ⨆ (_ : 0 < r ∧ r < 1), eLpNormFixed
           (fun θ : ℝ => f.1 (r * exp (I * θ))) p μ) r)
        exact le_antisymm (by simpa [hHardy] using hle) bot_le
      have hmeas : AEStronglyMeasurable (fun θ : ℝ => f.1 (r * exp (I * θ))) μ :=
        radial_aestronglyMeasurable f.2.1.continuousOn ⟨hr0, hr1⟩ μ
      have hzero : f.1 (r * exp (I * θ)) = 0 := by
        have hc : ENNReal.ofReal (1 / (2 * π)) ≠ 0 := by
          exact ne_of_gt (ENNReal.ofReal_pos.mpr (by positivity))
        have hae : (fun θ : ℝ => f.1 (r * exp (I * θ))) =ᵐ[
              volume.restrict (Ico 0 (2 * π))] 0 := by
          exact (MeasureTheory.Measure.ae_ennreal_smul_measure_iff hc).1
            ((eLpNormFixed_eq_zero_iff hmeas hp_ne_zero).1 hradial_zero)
        have hcont : Continuous (fun θ : ℝ => f.1 (r * exp (I * θ))) :=
          radial_cont f.2.1.continuousOn ⟨hr0, hr1⟩
        have hEqOn : EqOn (fun θ : ℝ => f.1 (r * exp (I * θ))) 0 (Ico 0 (2 * π)) := by
          exact Measure.eqOn_of_ae_eq hae hcont.continuousOn continuous_const.continuousOn
             (Ico_subset_closure_interior 0 (2 * π))
        exact hEqOn hθ
      simpa [hz_repr] using hzero
    have hpunctured' : ∀ z ≠ 0, f.1 z = 0 := by
      intro z hz0
      by_cases hz : z ∈ unitDisc
      · exact hpunctured z hz hz0
      · exact f.2.2.2 z hz
    have hcont : Continuous f.1 := by
      rw [continuous_iff_continuousAt]
      intro z
      by_cases hz0 : z = 0
      · subst z
        have h0_mem : 0 ∈ unitDisc := by simp [unitDisc]
        exact f.2.1.continuousOn.continuousAt (Metric.isOpen_ball.mem_nhds h0_mem)
      · have hnear : f.1 =ᶠ[nhds z] fun _ : ℂ => (0 : E) := by
          filter_upwards [isOpen_ne.mem_nhds hz0] with y hy
          exact hpunctured' y hy
        exact continuousAt_const.congr hnear.symm
    have hf_zero_ae : f.1 =ᵐ[volume] 0 := by
      filter_upwards [Measure.ae_ne (volume : Measure ℂ) (0 : ℂ)] with z hz
      exact hpunctured' z hz
    ext z
    exact congr_fun (Measure.eq_of_ae_eq hf_zero_ae hcont continuous_const) z
  . intro h; rw [h]; exact norm_zero p

lemma dist_eq_norm (p : ℝ≥0∞) (f g : HpDisc (E := E) p) :
    dist f g = ‖-f + g‖ := by rfl

lemma dist_self (p : ℝ≥0∞) (f : HpDisc (E := E) p) :
    dist f f = 0 := by rw [dist_eq_norm, neg_add_cancel f]; simp only [norm_zero]

lemma dist_comm (p : ℝ≥0∞) (f g : HpDisc (E := E) p) :
    dist f g = dist g f := by
  simp_rw [dist_eq_norm]; simpa [add_comm] using (norm_neg p (-g + f))

lemma dist_triangle (p : ℝ≥0∞) (f g h : HpDisc (E := E) p) :
    dist f h ≤ dist f g + dist g h := by
  simp_rw [dist_eq_norm]
  have hfgh : -f + h = (-f + g) + (-g + h) := by abel
  rw [hfgh]; exact norm_add_le p (-f + g) (-g + h)

lemma eq_of_dist_eq_zero (p : ℝ≥0∞) {f g : HpDisc (E := E) p}
  (hfg : dist f g = 0) [Fact (1 ≤ p)] : f = g := by
  rw [dist_eq_norm] at hfg
  have hsub : g - f = 0 := by
    simpa [sub_eq_add_neg, add_comm] using ((norm_eq_zero_iff p).1 hfg : -f + g = 0)
  simpa [eq_comm] using (sub_eq_zero.mp hsub : g = f)

instance instMetricSpace (p : ℝ≥0∞) [Fact (1 ≤ p)] :
    MetricSpace (HpDisc (E := E) p) where
  dist := dist
  dist_self := dist_self p
  dist_comm := dist_comm p
  dist_triangle := dist_triangle p
  eq_of_dist_eq_zero := fun {x y} h => eq_of_dist_eq_zero p h

instance instNormedAddCommGroup (p : ℝ≥0∞) [Fact (1 ≤ p)] :
    NormedAddCommGroup (HpDisc (E := E) p) where
  dist_eq := fun _ _ => rfl


end HpDisc
end HardySpace
