import Mathlib.Analysis.Complex.CauchyIntegral
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Data.ENNReal.Real
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Function.LpSeminorm.Defs
import Mathlib.Analysis.Analytic.Constructions

-- ## Remark: This file is mostly generated by Codex, an AI-agent developed by Openai.

/-!
# Classical Hardy space `H^p` on unit disc in ℂ


-/


noncomputable section

open scoped Real ENNReal
open MeasureTheory Real Complex


variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]

/-- The open unit disc in `ℂ`, represented as the metric ball of radius `1` around `0`. -/
def unitDisc : Set ℂ :=
  Metric.ball (0 : ℂ) 1

namespace HardySpace


/--
The Hardy `p`-norm on the unit disc.
-/
def hardyNorm {E : Type*} [NormedAddCommGroup E]
    (f : ℂ → E) (p : ℝ≥0∞) : ℝ≥0∞ :=
  if p = 0 then 0
  else if p = ∞ then ⨆ z : unitDisc, ENNReal.ofReal ‖f z.1‖
  else ⨆ (r : ℝ) (_ : 0 < r ∧ r < 1),
    eLpNorm (fun (θ : ℝ) ↦ f (r * exp (I * θ))) p
   (ENNReal.ofReal (1 / (2 * π)) • volume.restrict (Set.Ico 0 (2 * π)))
     ^ min p.toReal 1

-- I think it will be nice to split the case of `p = ∞` as otherwise, `∞.toReal = 0`
-- and we will have `hardyNorm f ∞` to be meaningless.

/-- Hardy `∞`-norm on the unit disc is equal to the supremum norm on the disc. -/
lemma hardyNorm_top_eq_Sup_norm
    {f : ℂ → E}
    (hf : ContinuousOn f unitDisc) :
    hardyNorm f ∞ = ⨆ z : unitDisc, ENNReal.ofReal ‖f z.1‖ := by sorry
    /-have hle : hardyNorm f ∞ ≤ ⨆ z : unitDisc, ENNReal.ofReal ‖f z.1‖ := by sorry
     /-unfold hardyNorm
     refine iSup_le ?_
     intro r
     refine iSup_le ?_
     intro hr
     rw [MeasureTheory.eLpNorm_exponent_top, MeasureTheory.eLpNormEssSup_eq_essSup_enorm]
     apply essSup_le_of_ae_le
     filter_upwards with θ
     rcases hr with ⟨hr0, hr1⟩

    --have hz : r * Complex.exp (Complex.I * θ) ∈ unitDisc := by sorry
    --exact le_iSup_of_le ⟨r * Complex.exp (Complex.I * θ), hz⟩ le_rfl-/
    have hre : ⨆ z : unitDisc, ENNReal.ofReal ‖f z.1‖ ≤ hardyNorm f ∞ := by sorry
    exact le_antisymm hle hre-/

/-- Membership in the Hardy space `H^p` on the unit disc. -/
def MemHpDisc
    (p : ℝ≥0∞) (f : ℂ → E) : Prop :=
  AnalyticOn ℂ f unitDisc ∧ hardyNorm f p < ∞

/-- Membership in `H^∞`, the space of bounded analytic functions on unit disc. -/
abbrev MemHInfinityDisc (f : ℂ → E) : Prop :=
  MemHpDisc ∞ f

/-- `H^p` space over unit disc. -/
def HpDisc (p : ℝ≥0∞) : Submodule ℂ (ℂ → E) where
  carrier := {f : ℂ → E | MemHpDisc (E := E) p f}
  add_mem' := by
     intro a b ha hb
     unfold MemHpDisc at *
     rw [Set.mem_setOf_eq] at *
     rcases ha with ⟨ha_ana , ha_norm⟩
     rcases hb with ⟨hb_ana , hb_norm⟩
     constructor
     . exact AnalyticOn.add ha_ana hb_ana
     . unfold hardyNorm at *
       sorry
  zero_mem' := by
    rw [Set.mem_setOf_eq]
    unfold MemHpDisc
    constructor
    . exact analyticOn_const
    . unfold hardyNorm
      by_cases hp : p = 0
      . simp [hp]
      . simp [hp]; by_cases hi : p = ∞
        . simp [hi]
        . simp [hi]; rw [ENNReal.zero_rpow_of_pos ?_]; simp; simp;
          -- why I have to `simp` twice here
          rw [ENNReal.toReal_pos_iff]
          rw [← ne_eq p 0] at hp
          rw [← ne_eq p ⊤] at hi
          constructor
          . exact pos_of_ne_zero hp
          . exact Ne.lt_top' (id (Ne.symm hi))
  smul_mem' := by
     intro c f hf
     rw [Set.mem_setOf] at *
     unfold MemHpDisc at *
     rcases hf with ⟨hf_an, hf_norm⟩
     constructor
     . exact AnalyticOn.const_smul hf_an
     . unfold hardyNorm at *
       by_cases hp : p = 0
       . simp [hp]
       . simp [hp] at *; by_cases hi : p = ∞
         . simp [hi] at *; sorry
         . simp [hi] at *; sorry






namespace HpDisc


instance instNorm (p : ℝ≥0∞) : Norm (HpDisc (E := E) p) where
  norm f := (hardyNorm (E := E) f.1 p).toReal

instance instDist (p : ℝ≥0∞)  : Dist (HpDisc (E := E) p) where
  dist f g := ‖- f + g‖

instance instEDist (p : ℝ≥0∞)  : EDist (HpDisc (E := E) p) where
  edist f g := hardyNorm (E := E) (f.1 - g.1) p


@[simp] lemma norm_def (p : ℝ≥0∞) (f : HpDisc (E := E) p)  :
    ‖f‖ = (hardyNorm (E := E) f.1 p).toReal := rfl

@[simp] lemma norm_zero (p : ℝ≥0∞)  :
    ‖(0 : HpDisc (E := E) p)‖ = 0 := by
  simp [hardyNorm]
  by_cases hp : p = 0
  . simp [hp]
  . simp [hp]; by_cases hi : p = ∞
    . simp [hi]
    . simp [hi]
      rw [ENNReal.zero_rpow_of_pos ?_]
      . simp
      . apply lt_min
        . rw [ENNReal.toReal_pos_iff]
          constructor
          . rw [pos_iff_ne_zero]; simpa
          . rw [lt_top_iff_ne_top]; simpa
        . exact Real.zero_lt_one

@[simp] lemma norm_neg (p : ℝ≥0∞) (f : HpDisc (E := E) p) :
    ‖-f‖ = ‖f‖ := by
  simp [hardyNorm]
  by_cases hp : p = 0
  . simp [hp]
  . simp [hp]; by_cases hi : p = ∞
    . simp [hi]
    . simp [hi]
      have eLpNorm_radial_neg (p : ℝ≥0∞) (μ : Measure ℝ) (f : ℂ → E) (r : ℝ) :
       eLpNorm (fun θ : ℝ => - f (↑r * cexp (I * ↑θ))) p μ
      = eLpNorm (fun θ : ℝ => f (↑r * cexp (I * ↑θ))) p μ := by
        sorry
      congr; ext r; congr; ext x; congr 1; exact eLpNorm_radial_neg p
        ((ENNReal.ofReal (π⁻¹ * 2⁻¹)) • volume.restrict (Set.Ico 0 (2 * π))) f.1 r

lemma norm_add_le (p : ℝ≥0∞)
    (f g : HpDisc (E := E) p) :
    ‖f + g‖ ≤ ‖f‖ + ‖g‖ := by
  sorry

lemma eq_zero_of_norm_eq_zero (p : ℝ≥0∞)
    {f : HpDisc (E := E) p} (h : ‖f‖ = 0) :
    f = 0 := by
  sorry

lemma dist_eq_norm (p : ℝ≥0∞) (f g : HpDisc (E := E) p)  :
    dist f g = ‖- f + g‖ := rfl

lemma dist_self (p : ℝ≥0∞) (f : HpDisc (E := E) p)  :
    dist f f = 0 := by
  sorry

lemma dist_comm (p : ℝ≥0∞) (f g : HpDisc (E := E) p)  :
    dist f g = dist g f := by
  sorry

lemma dist_triangle (p : ℝ≥0∞)
    (f g h : HpDisc (E := E) p) :
    dist f h ≤ dist f g + dist g h := by
  sorry

lemma eq_of_dist_eq_zero (p : ℝ≥0∞)
    {f g : HpDisc (E := E) p} (hfg : dist f g = 0) :
    f = g := by
  sorry


instance instMetricSpace (p : ℝ≥0∞) :
    MetricSpace (HpDisc (E := E) p) where
  dist := dist
  dist_self := dist_self p
  dist_comm := dist_comm p
  dist_triangle := dist_triangle p
  eq_of_dist_eq_zero := eq_of_dist_eq_zero p

instance instNormedAddCommGroup (p : ℝ≥0∞) [Fact (1 ≤ p)] :
     NormedAddCommGroup (HpDisc (E := E) p) where
   dist_eq := fun _ _ => rfl


end HpDisc
end HardySpace
