import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls
import Mathlib.Analysis.Normed.Module.Connected
import Mathlib.Analysis.InnerProductSpace.Harmonic.Basic

/-!
# Maximum and Comparison principles of harmonic functions
-/

-- # This file is generated by codex without careful review yet

open MeasureTheory Metric Set Real Filter
open scoped ENNReal Topology

noncomputable section

-- # General case on E (rather than ℂ)



-- Here are some topological lemmas that will be used later:

variable {X : Type*} [TopologicalSpace X]

/-- If `s` is open, a point of `closure s` that is not on the frontier is actually in `s`. -/
lemma mem_of_mem_closure_not_mem_frontier_of_isOpen
  {s : Set X} {x : X} (hs_open : IsOpen s)
  (hx_closure : x ∈ closure s) (hx_not_frontier : x ∉ frontier s) :
  x ∈ s := by
  by_contra hx_not_mem
  exact hx_not_frontier (by
    rw [hs_open.frontier_eq]
    exact ⟨hx_closure, hx_not_mem⟩)

/-- If a function is continuous on `closure s` and constant on `s`, then it is constant on
`closure s`. -/
lemma eqOn_closure_of_eqOn_of_continuousOn
  {u : X → ℝ} {s : Set X} {c : ℝ}
  (hu_cont : ContinuousOn u (closure s))
  (hu_const : ∀ y ∈ s, u y = c) :
  ∀ y ∈ closure s, u y = c := by
  have hclosed : IsClosed {y | y ∈ closure s ∧ u y = c} := by
    simpa [Set.mem_setOf_eq] using
      (isClosed_closure.isClosed_eq hu_cont continuousOn_const)
  have hsubset : s ⊆ {y | y ∈ closure s ∧ u y = c} := by
    intro y hy
    exact ⟨subset_closure hy, hu_const y hy⟩
  have hclosure_subset :
      closure s ⊆ {y | y ∈ closure s ∧ u y = c} :=
    closure_minimal hsubset hclosed
  intro y hy
  exact (hclosure_subset hy).2







variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]
  [MeasurableSpace E] [BorelSpace E]
variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

def ballAverage (u : E → F) (x : E) (r : ℝ) : F :=
   ((volume (ball x r)).toReal)⁻¹ • ∫ y in ball x r, u y ∂volume

/-- Mean value property for ball averages: a harmonic function on a neighbourhood of the closed
ball has average over the ball equal to its value at the center. -/
theorem HarmonicOnNhd.ballAverage_eq {f : E → F} {c : E} {R : ℝ}
(hf : InnerProductSpace.HarmonicOnNhd f (closedBall c |R|)) :
  ballAverage f c R = f c := sorry

/-- A local mean-value property implies harmonicity. This is the converse direction to
`HarmonicOnNhd.ballAverage_eq`. -/
theorem HarmonicOnNhd_of_ballAverage_eq {u : E → F} {s : Set E}
    (hs : IsOpen s) (hcont : ContinuousOn u s)
    (hmean : ∀ x ∈ s, ∃ ε > 0, ∀ r (_ : 0 < r ∧ r < ε), ballAverage u x r = u x) :
    InnerProductSpace.HarmonicOnNhd u s := by
  sorry

/-- If a continuous function is bounded above by `M` on a closed ball and is strictly below `M`
somewhere in the corresponding open ball, then its ball average is strictly below `M`. -/
lemma ballAverage_lt_of_forall_le_of_exists_lt
  {u : E → ℝ} {x : E} {r M : ℝ}
  (hr : 0 < r)
  (hu_cont : ContinuousOn u (closedBall x r))
  (hu_le : ∀ y ∈ closedBall x r, u y ≤ M)
  (hu_lt : ∃ y ∈ ball x r, u y < M) :
  ballAverage u x r < M := by
  have hball_ne_top : volume (ball x r) ≠ ∞ := measure_ball_lt_top.ne
  have hball_pos : 0 < volume (ball x r) := measure_ball_pos volume x hr
  have hball_toReal_pos : 0 < (volume (ball x r)).toReal :=
    ENNReal.toReal_pos hball_pos.ne' hball_ne_top
  have hu_int_closed : IntegrableOn u (closedBall x r) volume :=
    hu_cont.integrableOn_compact (isCompact_closedBall x r)
  have hu_int : IntegrableOn u (ball x r) volume :=
    hu_int_closed.mono_set ball_subset_closedBall
  have hconst_int : IntegrableOn (fun _ : E => M) (ball x r) volume :=
    integrableOn_const hball_ne_top
  have hdiff_int : IntegrableOn (fun y => M - u y) (ball x r) volume :=
    hconst_int.sub hu_int
  have hdiff_nonneg_ae : 0 ≤ᵐ[volume.restrict (ball x r)] fun y => M - u y :=
    ae_restrict_of_forall_mem measurableSet_ball fun y hy =>
      sub_nonneg.mpr (hu_le y (ball_subset_closedBall hy))
  rcases hu_lt with ⟨y₀, hy₀_ball, hy₀_lt⟩
  have hy₀_closed : y₀ ∈ closedBall x r := ball_subset_closedBall hy₀_ball
  have hu_cont_y₀ : ContinuousAt u y₀ :=
    hu_cont.continuousAt (Metric.closedBall_mem_nhds_of_mem hy₀_ball)
  have hlt_nhds : {y | u y < M} ∈ 𝓝 y₀ :=
    hu_cont_y₀ (Iio_mem_nhds hy₀_lt)
  have hgood_nhds : ball x r ∩ {y | u y < M} ∈ 𝓝 y₀ :=
    inter_mem (isOpen_ball.mem_nhds hy₀_ball) hlt_nhds
  rcases Metric.mem_nhds_iff.mp hgood_nhds with ⟨ε, hε_pos, hε_sub⟩
  have hsmall_sub : ball y₀ ε ⊆ Function.support (fun y => M - u y) ∩ ball x r := by
    intro y hy
    rcases hε_sub hy with ⟨hy_ball, hy_lt⟩
    exact ⟨by
      dsimp [Function.support]
      exact (sub_pos.mpr (by simpa using hy_lt)).ne', hy_ball⟩
  have hsupport_pos : 0 < volume (Function.support (fun y => M - u y) ∩ ball x r) :=
    (measure_ball_pos volume y₀ hε_pos).trans_le (measure_mono hsmall_sub)
  have hdiff_integral_pos : 0 < ∫ y in ball x r, M - u y ∂volume :=
    (setIntegral_pos_iff_support_of_nonneg_ae hdiff_nonneg_ae hdiff_int).2 hsupport_pos
  have hdiff_integral_eq :
      ∫ y in ball x r, M - u y ∂volume =
        (volume (ball x r)).toReal * M - ∫ y in ball x r, u y ∂volume := by
    rw [integral_sub, setIntegral_const, smul_eq_mul]
    · rfl
    · exact hconst_int
    · exact hu_int
  have hint_lt : ∫ y in ball x r, u y ∂volume < (volume (ball x r)).toReal * M := by
    nlinarith [hdiff_integral_pos, hdiff_integral_eq]
  rw [ballAverage, smul_eq_mul, inv_mul_eq_div]
  exact (div_lt_iff₀ hball_toReal_pos).mpr (by
    rw [mul_comm]
    exact hint_lt)

/-- If a harmonic function attains a maximum at `a` on an open set `s`, then its maximum level set
is open in the subtype topology on `s`. -/
lemma isOpen_maxLevelSet_of_harmonicOnNhd_isMaxOn_general
  {v : E → ℝ} {s : Set E} {a : E}
  (hs_open : IsOpen s)
  (hv : InnerProductSpace.HarmonicOnNhd v s)
  (hmax : ∀ y ∈ s, v y ≤ v a) :
  IsOpen ({x : s | v x = v a} : Set s) := by
  rw [Metric.isOpen_iff]
  intro x hxT
  rcases Metric.nhds_basis_closedBall.mem_iff.mp (hs_open.mem_nhds x.property) with
    ⟨r, hr_pos, hr_sub⟩
  refine ⟨r, hr_pos, ?_⟩
  intro y hy
  have hy_ball : (y : E) ∈ ball (x : E) r := by
    simpa only [Metric.mem_ball, Subtype.dist_eq] using hy
  have hclosed_sub : closedBall (x : E) r ⊆ s := hr_sub
  have hmean : ballAverage v (x : E) r = v (x : E) := by
    have hR : |r| = r := abs_of_pos hr_pos
    have hclosed_sub_abs : closedBall (x : E) |r| ⊆ s := by
      simpa [hR] using hclosed_sub
    simpa [hR] using HarmonicOnNhd.ballAverage_eq (hv.mono hclosed_sub_abs)
  have hv_le : ∀ z ∈ closedBall (x : E) r, v z ≤ v (x : E) := by
    intro z hz
    have hz_s : z ∈ s := hclosed_sub hz
    calc
      v z ≤ v a := hmax z hz_s
      _ = v (x : E) := hxT.symm
  by_contra hy_not
  have hy_lt : v (y : E) < v (x : E) := by
    have hy_ne : v (y : E) ≠ v (x : E) := by
      intro hy_eq
      apply hy_not
      exact hy_eq.trans hxT
    exact lt_of_le_of_ne (hv_le (y : E) (ball_subset_closedBall hy_ball)) hy_ne
  have havg_lt : ballAverage v (x : E) r < v (x : E) :=
    ballAverage_lt_of_forall_le_of_exists_lt hr_pos
      (hv.continuousOn.mono hclosed_sub) hv_le ⟨(y : E), hy_ball, hy_lt⟩
  rw [hmean] at havg_lt
  exact (lt_irrefl (v (x : E))) havg_lt

/-- Strong maximum/minimum principle for real-valued harmonic functions: if a harmonic function on
a connected domain attains an interior maximum or minimum, then it is constant on the domain. -/
theorem harmonic_maximum_minimum_principle_general
  {u : E → ℝ} {s : Set E}
  (hs_open : IsOpen s) (hs_conn : IsPreconnected s)
  (hu : InnerProductSpace.HarmonicOnNhd u s)
  (h_extreme : (∃ x ∈ s, ∀ y ∈ s, u y ≤ u x) ∨ (∃ x ∈ s, ∀ y ∈ s, u x ≤ u y)) :
  ∃ c : ℝ, ∀ x ∈ s, u x = c := by
  have max_case : ∀ {v : E → ℝ}, InnerProductSpace.HarmonicOnNhd v s →
      (∃ a ∈ s, ∀ y ∈ s, v y ≤ v a) → ∃ c : ℝ, ∀ x ∈ s, v x = c := by
    intro v hv hmax
    rcases hmax with ⟨a, ha, hmax⟩
    let T : Set s := {x | v x = v a}
    haveI : PreconnectedSpace s := Subtype.preconnectedSpace hs_conn
    have hT_nonempty : T.Nonempty := ⟨⟨a, ha⟩, rfl⟩
    have hT_closed : IsClosed T := by
      have hv_cont : ContinuousOn v s := hv.continuousOn
      have hv_cont_s : Continuous (s.restrict v) := hv_cont.restrict
      simpa [T, Set.restrict_apply] using isClosed_eq hv_cont_s continuous_const
    have hT_open : IsOpen T := by
      simpa [T] using isOpen_maxLevelSet_of_harmonicOnNhd_isMaxOn_general hs_open hv hmax
    have hT_univ : T = Set.univ := IsClopen.eq_univ ⟨hT_closed, hT_open⟩ hT_nonempty
    refine ⟨v a, ?_⟩
    intro x hx
    have : (⟨x, hx⟩ : s) ∈ T := by
      rw [hT_univ]
      exact mem_univ _
    simpa [T] using this
  rcases h_extreme with hmax | hmin
  · exact max_case hu hmax
  · rcases hmin with ⟨a, ha, hmin⟩
    have hmax_neg : ∃ x ∈ s, ∀ y ∈ s, (-u) y ≤ (-u) x := by
      refine ⟨a, ha, ?_⟩
      intro y hy
      exact neg_le_neg (hmin y hy)
    rcases max_case hu.neg hmax_neg with ⟨c, hc⟩
    refine ⟨-c, ?_⟩
    intro x hx
    have hcx := hc x hx
    change -u x = c at hcx
    linarith


/-- A harmonic function on a bounded connected domain achieves its maximum on the boundary. -/
lemma harmonic_exists_isMaxOn_frontier_of_bounded_domain
  [Nontrivial E] {u : E → ℝ} {s : Set E}
  (hs_open : IsOpen s) (hs_conn : IsPreconnected s)
  (hs_nonempty : s.Nonempty)
  (hs_bdd : Bornology.IsBounded s)
  (hu_cont : ContinuousOn u (closure s))
  (hu_harm : InnerProductSpace.HarmonicOnNhd u s) :
  ∃ z ∈ frontier s, IsMaxOn u (closure s) z := by
  have hcompact : IsCompact (closure s) := hs_bdd.isCompact_closure
  rcases hcompact.exists_isMaxOn hs_nonempty.closure hu_cont with
    ⟨a, ha_closure, ha_max⟩
  by_cases ha_frontier : a ∈ frontier s
  · exact ⟨a, ha_frontier, ha_max⟩
  · have ha_s : a ∈ s :=
      mem_of_mem_closure_not_mem_frontier_of_isOpen hs_open ha_closure ha_frontier
    have h_extreme :
        (∃ x ∈ s, ∀ y ∈ s, u y ≤ u x) ∨
          (∃ x ∈ s, ∀ y ∈ s, u x ≤ u y) := by
      left
      refine ⟨a, ha_s, ?_⟩
      intro y hy
      exact ha_max (subset_closure hy)
    rcases harmonic_maximum_minimum_principle_general
        hs_open hs_conn hu_harm h_extreme with ⟨C, hC⟩
    have hC_closure : ∀ y ∈ closure s, u y = C :=
      eqOn_closure_of_eqOn_of_continuousOn hu_cont hC
    have hs_ne_univ : s ≠ Set.univ := by
      intro hs_eq
      have hbdd_univ : Bornology.IsBounded (Set.univ : Set E) := by
        simpa [hs_eq] using hs_bdd
      exact NormedSpace.unbounded_univ ℝ E hbdd_univ
    have hfrontier_nonempty : (frontier s).Nonempty :=
      (nonempty_frontier_iff).2 ⟨hs_nonempty, hs_ne_univ⟩
    rcases hfrontier_nonempty with ⟨z, hz_frontier⟩
    refine ⟨z, hz_frontier, ?_⟩
    intro y hy
    change u y ≤ u z
    rw [hC_closure y hy, hC_closure z (frontier_subset_closure hz_frontier)]

/-- A harmonic function on a bounded connected domain achieves its minimum on the boundary. -/
lemma harmonic_exists_isMinOn_frontier_of_bounded_domain
  [Nontrivial E] {u : E → ℝ} {s : Set E}
  (hs_open : IsOpen s) (hs_conn : IsPreconnected s)
  (hs_nonempty : s.Nonempty)
  (hs_bdd : Bornology.IsBounded s)
  (hu_cont : ContinuousOn u (closure s))
  (hu_harm : InnerProductSpace.HarmonicOnNhd u s) :
  ∃ w ∈ frontier s, IsMinOn u (closure s) w := by
  rcases harmonic_exists_isMaxOn_frontier_of_bounded_domain (u := -u) (s := s)
      hs_open hs_conn hs_nonempty hs_bdd hu_cont.neg hu_harm.neg with
    ⟨w, hw_frontier, hw_max_neg⟩
  refine ⟨w, hw_frontier, ?_⟩
  intro y hy
  simpa using hw_max_neg hy

/-- A harmonic function on a bounded connected domain achieves its maximum and minimum on the
boundary. -/
theorem harmonic_exists_isMaxOn_isMinOn_frontier_of_bounded_domain
  [Nontrivial E] {u : E → ℝ} {s : Set E}
  (hs_open : IsOpen s) (hs_conn : IsPreconnected s)
  (hs_nonempty : s.Nonempty)
  (hs_bdd : Bornology.IsBounded s)
  (hu_cont : ContinuousOn u (closure s))
  (hu_harm : InnerProductSpace.HarmonicOnNhd u s) :
  (∃ z ∈ frontier s, IsMaxOn u (closure s) z)
    ∧ (∃ w ∈ frontier s, IsMinOn u (closure s) w) :=
    ⟨harmonic_exists_isMaxOn_frontier_of_bounded_domain
      hs_open hs_conn hs_nonempty hs_bdd hu_cont hu_harm,
    harmonic_exists_isMinOn_frontier_of_bounded_domain
      hs_open hs_conn hs_nonempty hs_bdd hu_cont hu_harm⟩

/-- Maximum principle on a bounded connected domain: if a harmonic function is continuous on the
closure of the domain and is bounded above by `M` on the frontier, then it is bounded above by `M`
throughout the domain. -/
theorem harmonic_maximum_principle_on_domain
  [Nontrivial E] {u : E → ℝ} {s : Set E} { M : ℝ}
  (hs_open : IsOpen s) (hs_conn : IsPreconnected s)
  (hs_nonempty : s.Nonempty)
  (hs_bdd : Bornology.IsBounded s)
  (hu : InnerProductSpace.HarmonicOnNhd u s)
  (huc : ContinuousOn u (closure s)):
  (∀ y ∈ frontier s, u y ≤ M) → ∀ y ∈ s, u y ≤ M := by
  intro hbd y hy
  rcases harmonic_exists_isMaxOn_frontier_of_bounded_domain
      hs_open hs_conn hs_nonempty hs_bdd huc hu with
    ⟨z, hz_frontier, hz_max⟩
  exact (hz_max (subset_closure hy)).trans (hbd z hz_frontier)

/-- Comparison principle on a bounded connected domain: if two harmonic functions are continuous on
the closure of the domain and `u ≤ v` on the frontier, then `u ≤ v` throughout the domain. -/
theorem harmonic_comparison_principle_on_domain
  [Nontrivial E] {u v : E → ℝ} {s : Set E}
  (hs_open : IsOpen s) (hs_conn : IsPreconnected s)
  (hs_nonempty : s.Nonempty)
  (hs_bdd : Bornology.IsBounded s)
  (hu : InnerProductSpace.HarmonicOnNhd u s)
  (hv : InnerProductSpace.HarmonicOnNhd v s)
  (huc : ContinuousOn u (closure s))
  (hvc : ContinuousOn v (closure s)):
  (∀ y ∈ frontier s, u y ≤ v y) → ∀ y ∈ s, u y ≤ v y := by
  intro hbd y hy
  have hdiff_harm : InnerProductSpace.HarmonicOnNhd (u - v) s := hu.sub hv
  have hdiff_cont : ContinuousOn (u - v) (closure s) := huc.sub hvc
  have hdiff_bd : ∀ y ∈ frontier s, (u - v) y ≤ 0 := by
    intro y hy
    exact sub_nonpos.mpr (hbd y hy)
  have hdiff_dom : ∀ y ∈ s, (u - v) y ≤ 0 :=
    harmonic_maximum_principle_on_domain
      hs_open hs_conn hs_nonempty hs_bdd hdiff_harm hdiff_cont hdiff_bd
  exact sub_nonpos.mp (hdiff_dom y hy)


-- # Here are the specific cases over ball:

/-- Maximum principle on a ball in `ℂ`: if a harmonic function is continuous on the closed ball
and is bounded above by `M` on the sphere, then it is bounded above by `M` inside the ball. -/
theorem harmonic_maximum_principle_on_ball
  {u : E → ℝ} {x : E} {r M : ℝ} [Nontrivial E]
  (hu : InnerProductSpace.HarmonicOnNhd u (ball x r))
  (huc : ContinuousOn u (closedBall x r)):
  (∀ y ∈ sphere x r, u y ≤ M) → ∀ y ∈ ball x r, u y ≤ M := by
  intro hbd y hy
  have hr : 0 < r := pos_of_mem_ball hy
  have huc_closure : ContinuousOn u (closure (ball x r)) := by
    simpa [closure_ball x hr.ne'] using huc
  have hbd_frontier : ∀ z ∈ frontier (ball x r), u z ≤ M := by
    intro z hz
    exact hbd z (by simpa [frontier_ball x hr.ne'] using hz)
  exact harmonic_maximum_principle_on_domain
    (s := ball x r) (u := u) (M := M)
    isOpen_ball isPreconnected_ball ⟨x, mem_ball_self hr⟩ isBounded_ball
    hu huc_closure hbd_frontier y hy

/-- Comparison principle on a ball in `ℂ`: if two harmonic functions are continuous on the closed
ball and `u ≤ v` on the sphere, then `u ≤ v` inside the ball. -/
theorem harmonic_comparison_principle_on_ball
  {u v : E → ℝ} {x : E} {r : ℝ} [Nontrivial E]
  (hu : InnerProductSpace.HarmonicOnNhd u (ball x r))
  (hv : InnerProductSpace.HarmonicOnNhd v (ball x r))
  (huc : ContinuousOn u (closedBall x r))
  (hvc : ContinuousOn v (closedBall x r)):
  (∀ y ∈ sphere x r, u y ≤ v y) → ∀ y ∈ ball x r, u y ≤ v y := by
  intro hbd y hy
  have hr : 0 < r := pos_of_mem_ball hy
  have huc_closure : ContinuousOn u (closure (ball x r)) := by
    simpa [closure_ball x hr.ne'] using huc
  have hvc_closure : ContinuousOn v (closure (ball x r)) := by
    simpa [closure_ball x hr.ne'] using hvc
  have hbd_frontier : ∀ z ∈ frontier (ball x r), u z ≤ v z := by
    intro z hz
    exact hbd z (by simpa [frontier_ball x hr.ne'] using hz)
  exact harmonic_comparison_principle_on_domain
    (s := ball x r) (u := u) (v := v)
    isOpen_ball isPreconnected_ball ⟨x, mem_ball_self hr⟩ isBounded_ball
    hu hv huc_closure hvc_closure hbd_frontier y hy
