import HardySpaceFormalization.Poisson_lemma
import Mathlib.Analysis.Complex.Harmonic.Poisson

/-!
# Harnack's inequality and Harnack's theorem

This file develops the Harnack estimates for nonnegative harmonic functions on a disc, and (later)
Harnack's theorem on monotone sequences of harmonic functions.

The classical reference is Rudin, *Real and Complex Analysis*, Theorem 11.11; Garnett invokes it
without proof in the course of Theorem I.6.7.

## Main results

* `harnack_le`, `le_harnack`, `harnack_inequality` : **Harnack's inequality**. If `u` is harmonic
  on a neighbourhood of `closedBall c R` and nonnegative on the boundary circle, then for `w`
  interior, with `ρ = ‖w - c‖`,
  `((R - ρ) / (R + ρ)) * u c ≤ u w ≤ ((R + ρ) / (R - ρ)) * u c`.

These come from the Poisson integral formula together with the two-sided Poisson kernel estimates
`le_poissonKernel_of_mem_ball` and `poissonKernel_le_of_mem_ball`, and the mean value property at
the centre.
-/

-- ## This is completely ai-generated by claude and completely without review at the moment
-- ## It is just a test file! 

noncomputable section

open Complex Metric Real Set MeasureTheory
open scoped Topology

variable {u : ℂ → ℝ} {R : ℝ} {w c : ℂ}

namespace InnerProductSpace

/-- The boundary data of a function harmonic on a closed ball is circle integrable. -/
private theorem circleIntegrable_of_harmonicOnNhd
    (hu : HarmonicOnNhd u (closedBall c R)) (hR : 0 ≤ R) :
    CircleIntegrable u c R :=
  (hu.continuousOn.mono sphere_subset_closedBall).circleIntegrable hR

/-- A constant multiple of that boundary data is circle integrable. -/
private theorem circleIntegrable_const_mul_of_harmonicOnNhd
    (hu : HarmonicOnNhd u (closedBall c R)) (hR : 0 ≤ R) (a : ℝ) :
    CircleIntegrable (fun z => a * u z) c R :=
  (continuousOn_const.mul (hu.continuousOn.mono sphere_subset_closedBall)).circleIntegrable hR

/-- The Poisson kernel times the boundary data of a harmonic function is circle integrable. -/
private theorem circleIntegrable_poissonKernel_mul_of_harmonicOnNhd
    (hu : HarmonicOnNhd u (closedBall c R)) (hw : w ∈ ball c R) :
    CircleIntegrable (fun z => poissonKernel c w z * u z) c R := by
  have hR : 0 ≤ R := dist_nonneg.trans (mem_ball.mp hw).le
  exact ContinuousOn.circleIntegrable hR
    ((continuousOn_poissonKernel_right_of_mem_ball hw).mul
      (hu.continuousOn.mono sphere_subset_closedBall))

/-- The circle average of a constant multiple. -/
private theorem circleAverage_const_mul (a : ℝ) (f : ℂ → ℝ) (c : ℂ) (R : ℝ) :
    circleAverage (fun z => a * f z) c R = a * circleAverage f c R := by
  simpa [smul_eq_mul] using circleAverage_fun_smul (a := a) (f := f) (c := c) (R := R)

/-- The Poisson integral formula at an interior point, written multiplicatively. -/
private theorem circleAverage_poissonKernel_mul_eq
    (hu : HarmonicOnNhd u (closedBall c R)) (hw : w ∈ ball c R) :
    circleAverage (fun z => poissonKernel c w z * u z) c R = u w := by
  simpa [Pi.smul_apply', smul_eq_mul, Pi.mul_def] using
    HarmonicOnNhd.circleAverage_poissonKernel_smul hu hw

/-- **Harnack's inequality**, upper half. A harmonic function that is nonnegative on the boundary
circle is bounded at an interior point by the Harnack factor times its value at the centre. -/
theorem harnack_le (hu : HarmonicOnNhd u (closedBall c R))
    (hnonneg : ∀ z ∈ sphere c R, 0 ≤ u z) (hw : w ∈ ball c R) :
    u w ≤ (R + ‖w - c‖) / (R - ‖w - c‖) * u c := by
  have hR : 0 ≤ R := dist_nonneg.trans (mem_ball.mp hw).le
  have habs : |R| = R := abs_of_nonneg hR
  have hmean : circleAverage u c R = u c :=
    HarmonicOnNhd.circleAverage_eq (R := R) (by rwa [habs])
  have hbound : ∀ z ∈ sphere c |R|,
      poissonKernel c w z * u z ≤ (R + ‖w - c‖) / (R - ‖w - c‖) * u z := by
    intro z hz
    rw [habs] at hz
    exact mul_le_mul_of_nonneg_right (poissonKernel_le_of_mem_ball hw hz) (hnonneg z hz)
  have hmono := circleAverage_mono
    (circleIntegrable_poissonKernel_mul_of_harmonicOnNhd hu hw)
    (circleIntegrable_const_mul_of_harmonicOnNhd hu hR _) hbound
  rwa [circleAverage_poissonKernel_mul_eq hu hw, circleAverage_const_mul, hmean] at hmono

/-- **Harnack's inequality**, lower half. A harmonic function that is nonnegative on the boundary
circle is bounded below at an interior point by the Harnack factor times its value at the
centre. -/
theorem le_harnack (hu : HarmonicOnNhd u (closedBall c R))
    (hnonneg : ∀ z ∈ sphere c R, 0 ≤ u z) (hw : w ∈ ball c R) :
    (R - ‖w - c‖) / (R + ‖w - c‖) * u c ≤ u w := by
  have hR : 0 ≤ R := dist_nonneg.trans (mem_ball.mp hw).le
  have habs : |R| = R := abs_of_nonneg hR
  have hmean : circleAverage u c R = u c :=
    HarmonicOnNhd.circleAverage_eq (R := R) (by rwa [habs])
  have hbound : ∀ z ∈ sphere c |R|,
      (R - ‖w - c‖) / (R + ‖w - c‖) * u z ≤ poissonKernel c w z * u z := by
    intro z hz
    rw [habs] at hz
    exact mul_le_mul_of_nonneg_right (le_poissonKernel_of_mem_ball hw hz) (hnonneg z hz)
  have hmono := circleAverage_mono
    (circleIntegrable_const_mul_of_harmonicOnNhd hu hR _)
    (circleIntegrable_poissonKernel_mul_of_harmonicOnNhd hu hw) hbound
  rwa [circleAverage_poissonKernel_mul_eq hu hw, circleAverage_const_mul, hmean] at hmono

/-- **Harnack's inequality** on a ball, both halves. -/
theorem harnack_inequality (hu : HarmonicOnNhd u (closedBall c R))
    (hnonneg : ∀ z ∈ sphere c R, 0 ≤ u z) (hw : w ∈ ball c R) :
    (R - ‖w - c‖) / (R + ‖w - c‖) * u c ≤ u w ∧
      u w ≤ (R + ‖w - c‖) / (R - ‖w - c‖) * u c :=
  ⟨le_harnack hu hnonneg hw, harnack_le hu hnonneg hw⟩

end InnerProductSpace
