import Mathlib.Analysis.Convex.Integral
import Mathlib.Algebra.Order.Archimedean.Basic
import Mathlib.Topology.Semicontinuity.Basic
import HardySpaceFormalization.Harmonic_max_principle
import HardySpaceFormalization.Poisson_lemma


/-!
# Subharmonic functions, mean-value test version

This file experiments with a direct mean-value definition of subharmonicity for
`WithBot ℝ`-valued functions.  It is intentionally kept separate from
`Subharmonic.lean`.

# Note : this file is currently mostly generated by codex without much review. It's a test file only.

-/

open MeasureTheory Metric Set Real Filter
open scoped ENNReal Topology

noncomputable section



variable {E : Type*} [NormedAddCommGroup E]


-- # First, we extend `Real.log` and `Real.exp` to the following functions

/-- The extended logarithm of the norm, with value `⊥` at the origin. -/
def logNormBot [DecidableEq E] : E → WithBot ℝ := fun z => if z = 0 then ⊥ else (log ‖z‖ : WithBot ℝ)

/-- The exponential map on `WithBot ℝ`, extended by sending `⊥` to `0`. -/
def expBot : WithBot ℝ → ℝ := fun x => if hx : x = ⊥ then 0 else exp (x.unbot hx)

lemma expBot_coe (x : ℝ) : expBot (x : WithBot ℝ) = exp x := by simp [expBot]

/-- Exponentiating `p * log ‖z‖`, with `logNormBot 0 = ⊥` and `expBot ⊥ = 0`,
recovers `‖z‖ ^ p`. -/
lemma exp_mul_logNorm_eq_norm_rpow {p : ℝ} (hp : 0 < p) (z : E) [DecidableEq E] :
  expBot (p * logNormBot z) = (‖z‖ ^ p : ℝ) := by
  by_cases hz : z = 0
  · have hp0 : (p : WithBot ℝ) ≠ 0 := by exact_mod_cast hp.ne'
    simp [expBot, logNormBot, hz, zero_rpow hp.ne', WithBot.mul_bot hp0]
  · have hnorm : 0 < ‖z‖ := norm_pos_iff.mpr hz
    have hlog : logNormBot z = (log ‖z‖ : WithBot ℝ) := by simp [logNormBot, hz]
    have hprod : p * (log ‖z‖ : WithBot ℝ) = ((p * log ‖z‖ : ℝ) : WithBot ℝ) := by simp
    rw [rpow_def_of_pos hnorm]
    rw [hlog, hprod, expBot_coe, mul_comm]

variable {s : Set E} {u : E → WithBot ℝ}

/-- Applying `expBot` to an upper semicontinuous `WithBot ℝ`-valued function preserves upper
semicontinuity. -/
lemma UpperSemicontinuousOn.expBot_mul (hu : UpperSemicontinuousOn u s) :
  UpperSemicontinuousOn (fun z => expBot (u z)) s := by
  intro x hx a hlt
  have hexpBot_nonneg : 0 ≤ expBot (u x) := by cases u x <;> simp [expBot, exp_nonneg]
  have ha_pos : 0 < a := lt_of_le_of_lt hexpBot_nonneg hlt
  have hx_log : u x < (log a : WithBot ℝ) := by
    cases hux : u x with
    | bot => simp
    | coe b =>
      refine WithBot.coe_lt_coe.mpr ((lt_log_iff_exp_lt ha_pos).mpr ?_)
      simpa [expBot, hux] using hlt
  have hlog_expBot : ∀ w : WithBot ℝ, w < (log a : WithBot ℝ) → expBot w < a := by
    intro w hw
    cases w with
    | bot => simpa [expBot] using ha_pos
    | coe b => simpa [expBot] using (Real.lt_log_iff_exp_lt ha_pos).mp (WithBot.coe_lt_coe.mp hw)
  filter_upwards [hu x hx (log a : WithBot ℝ) hx_log] with y hy
  exact hlog_expBot (u y) hy

/-- Coercing a real-valued upper semicontinuous function to `WithBot ℝ` preserves upper
semicontinuity. -/
lemma UpperSemicontinuousOn.withBot_coe {f : E → ℝ} (hf : UpperSemicontinuousOn f s) :
    UpperSemicontinuousOn (fun z => (f z : WithBot ℝ)) s := by
  intro x hx a hlt
  cases a with
  | bot =>
      exact False.elim (not_lt_bot hlt)
  | coe a =>
      have hlt_real : f x < a := WithBot.coe_lt_coe.mp hlt
      filter_upwards [hf x hx a hlt_real] with y hy
      exact WithBot.coe_lt_coe.mpr hy


/-- Multiplication by a nonnegative real constant preserves upper semicontinuity for `WithBot ℝ`-
valued functions. -/
lemma UpperSemicontinuousOn.const_mul {p : ℝ} (hp : 0 ≤ p)
  (hu : UpperSemicontinuousOn u s) : UpperSemicontinuousOn ((p : WithBot ℝ) • u) s := by
  by_cases hp0 : p = 0
  · simpa [hp0] using (upperSemicontinuousOn_const (s := s) (z := (0 : WithBot ℝ)))
  · have hp_pos : 0 < p := lt_of_le_of_ne hp (Ne.symm hp0)
    intro x hx a hlt
    cases a with
    | bot => exact False.elim (not_lt_bot hlt)
    | coe c =>
      have hx_div : u x < (c / p : WithBot ℝ) := by
        cases hux : u x with
        | bot => simp
        | coe b =>
          have hb : p * b < c := by
            exact WithBot.coe_lt_coe.mp (by simpa [hux] using hlt)
          exact WithBot.coe_lt_coe.mpr ((lt_div_iff₀' hp_pos).mpr hb)
      have hmul :
          ∀ w : WithBot ℝ, w < (c / p : WithBot ℝ) →
            (p : WithBot ℝ) * w < (c : WithBot ℝ) := by
        intro w hw
        cases w with
        | bot =>
          have hp_ne : (p : WithBot ℝ) ≠ 0 := by exact_mod_cast hp0
          simp [WithBot.mul_bot hp_ne]
        | coe b =>
          have hb : b < c / p := WithBot.coe_lt_coe.mp hw
          exact WithBot.coe_lt_coe.mpr ((lt_div_iff₀' hp_pos).mp hb)
      filter_upwards [hu x hx (c / p : WithBot ℝ) hx_div] with y hy
      exact hmul (u y) hy

lemma WithBot.add_lt_coe_add {x y : WithBot ℝ} {a b : ℝ}
    (hx : x < a) (hy : y < b) : x + y < a + b := by
  cases x with
  | bot => simp
  | coe x =>
      cases y with
      | bot => simp
      | coe y =>
          apply WithBot.coe_lt_coe.mpr
          linarith [WithBot.coe_lt_coe.mp hx, WithBot.coe_lt_coe.mp hy]

/-- The sum of two upper semicontinuous `WithBot ℝ`-valued functions is upper
semicontinuous. -/
lemma UpperSemicontinuousOn.withBot_add {v : E → WithBot ℝ}
    (hu : UpperSemicontinuousOn u s) (hv : UpperSemicontinuousOn v s) :
    UpperSemicontinuousOn (u + v) s := by
  intro x hx a hlt
  cases a with
  | bot => exact False.elim (not_lt_bot hlt)
  | coe c =>
      cases hux : u x with
      | bot =>
          cases hvx : v x with
          | bot =>
              filter_upwards
                [hu x hx (c : WithBot ℝ) (by simp [hux]),
                 hv x hx (0 : WithBot ℝ) (by simp [hvx])] with y hyu hyv
              exact (WithBot.add_lt_coe_add hyu hyv).trans_eq (by norm_num)
          | coe b =>
              filter_upwards
                [hu x hx (c - (b + 1) : WithBot ℝ) (by simp [hux]),
                 hv x hx ((b + 1 : ℝ) : WithBot ℝ)
                  (by simpa [hvx] using WithBot.coe_lt_coe.mpr (lt_add_one b))] with y hyu hyv
              apply (WithBot.add_lt_coe_add hyu hyv).trans_eq
              rw [← WithBot.coe_add]
              ring_nf
      | coe b =>
          cases hvx : v x with
          | bot =>
              filter_upwards
                [hu x hx ((b + 1 : ℝ) : WithBot ℝ)
                 (by simpa [hux] using WithBot.coe_lt_coe.mpr (lt_add_one b)),
                 hv x hx (c - (b + 1) : WithBot ℝ) (by simp [hvx])] with y hyu hyv
              apply (WithBot.add_lt_coe_add hyu hyv).trans_eq
              rw [← WithBot.coe_add]
              ring_nf
          | coe d =>
              have hsum : b + d < c := by
                exact WithBot.coe_lt_coe.mp (by simpa [hux, hvx] using hlt)
              let ε : ℝ := (c - (b + d)) / 2
              have hε_pos : 0 < ε := by
                dsimp [ε]; linarith
              filter_upwards
                [hu x hx (b + ε)
                  (by simpa [hux] using
                    WithBot.coe_lt_coe.mpr (lt_add_of_pos_right b hε_pos)),
                 hv x hx (d + ε)
                  (by simpa [hvx] using
                    WithBot.coe_lt_coe.mpr (lt_add_of_pos_right d hε_pos))] with y hyu hyv
              exact (WithBot.add_lt_coe_add hyu hyv).trans_eq (by
                exact congrArg ((↑) : ℝ → WithBot ℝ) (by
                  dsimp [ε]
                  ring))


-- # Now we define the subharmonic functions:

variable [InnerProductSpace ℝ E] [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]
variable {F : Type*} [NormedAddCommGroup F]

lemma WithBot.add_neg_coe_le_zero_iff (x : WithBot ℝ) (a : ℝ) :
    x + ((-a : ℝ) : WithBot ℝ) ≤ 0 ↔ x ≤ a := by
  cases x with
  | bot => simp
  | coe b =>
      constructor
      · intro h
        exact WithBot.coe_le_coe.mpr (by
          have hreal : b + -a ≤ 0 := WithBot.coe_le_coe.mp (by simpa using h)
          linarith)
      · intro h
        have hreal : b ≤ a := WithBot.coe_le_coe.mp h
        exact WithBot.coe_le_coe.mpr (by linarith)

/-- The integral of a `WithBot ℝ`-valued function over a set. If the `⊥` set has positive
measure, the integral is defined to be `⊥`; otherwise we integrate the real-valued representative
obtained by sending `⊥` to `0`. -/
def withBotIntegral (u : E → WithBot ℝ) (A : Set E) (μ : Measure E := volume) : WithBot ℝ :=
  if μ (A ∩ {x | u x = ⊥}) = 0 then
    ((∫ x in A, (u x).unbotD 0 ∂μ : ℝ) : WithBot ℝ)
  else ⊥

-- # Here I add another version of `withBotIntegral'` in order to manage junk value differently
open Classical in
def withBotIntegral' (u : E → WithBot ℝ) (A : Set E) (μ : Measure E := volume) : WithBot ℝ :=
  if μ (A ∩ {x | u x = ⊥}) = 0 ∧ IntegrableOn ((WithBot.unbotD 0) ∘ u) A μ then
      ((∫ x in A, (u x).unbotD 0 ∂μ : ℝ) : WithBot ℝ)
  else ⊥


notation "∫ᴮ " x ", " f:60 " ∂" μ:70 => withBotIntegral (fun x => f) Set.univ μ
notation "∫ᴮ " x ", " f:60 => withBotIntegral (fun x => f) Set.univ volume
notation "∫ᴮ " x " in " s ", " f:60 " ∂" μ:70 => withBotIntegral (fun x => f) s μ
notation "∫ᴮ " x " in " s ", " f:60 => withBotIntegral (fun x => f) s volume

/-- Ball average for `WithBot ℝ`-valued functions, using `withBotIntegral`.
For `r ≤ 0` this is just a total-definition junk value; the sub-mean property below only uses it
under the hypothesis `0 < r`. -/
def ballAverageWithBot (u : E → WithBot ℝ) (x : E) (r : ℝ) : WithBot ℝ :=
  ((volume (ball x r)).toReal)⁻¹ * (∫ᴮ y in ball x r, u y)

/-- For a real-valued function coerced to `WithBot ℝ`, the `WithBot` integral is just the ordinary
Bochner integral, coerced to `WithBot ℝ`. -/
lemma withBotIntegral_coe (u : E → ℝ) (A : Set E) (μ : Measure E := volume) :
    ∫ᴮ x in A, (u x : WithBot ℝ) ∂μ = ((∫ x in A, u x ∂μ : ℝ) : WithBot ℝ) := by
  simp [withBotIntegral, WithBot.unbotD]

omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E] [BorelSpace E] in
/-- If a `WithBot ℝ`-valued function agrees almost everywhere with a real-valued representative,
then the auxiliary real representative obtained by `(WithBot.unbotD 0)` is integrable wherever the
real representative is integrable. -/
lemma integrableOn_unbotD_of_eq_coe_ae
    {u : E → WithBot ℝ} {v : E → ℝ} {A : Set E} {μ : Measure E}
    (hv : IntegrableOn v A μ)(huv : ∀ᵐ x ∂μ.restrict A, u x = v x) :
    IntegrableOn ((WithBot.unbotD 0) ∘ u) A μ := by
  refine hv.congr_fun_ae ?_
  filter_upwards [huv] with x hx
  simp [hx, WithBot.unbotD]

omit [InnerProductSpace ℝ E] [FiniteDimensional ℝ E] in
/-- If `f` is continuous and nonzero on a compact set `K`, then
`(WithBot.unbotD 0) ∘ logNormBot ∘ f` is integrable on any finite-measure measurable subset of `K`. -/
lemma integrableOn_unbotD_logNormBot_comp_of_continuousOn_of_ne_on [DecidableEq F]
    {f : E → F} {A K : Set E} {μ : Measure E}
    (hf_cont : ContinuousOn f K) (hK : IsCompact K)
    (hA_meas : MeasurableSet A) (hA_sub : A ⊆ K) (hA_ne_top : μ A ≠ ∞)
    (hne : ∀ x ∈ K, f x ≠ 0) :
    IntegrableOn ((WithBot.unbotD 0) ∘ logNormBot ∘ f) A μ := by
  have hlog_cont : ContinuousOn (fun x => log ‖f x‖) K :=
    hf_cont.norm.log (fun x hx => norm_ne_zero_iff.mpr (hne x hx))
  have hlog_int : IntegrableOn (fun x => log ‖f x‖) A μ :=
    hlog_cont.integrableOn_of_subset_isCompact hK hA_meas hA_sub hA_ne_top
  refine integrableOn_unbotD_of_eq_coe_ae hlog_int ?_
  filter_upwards [ae_restrict_mem hA_meas] with x hx
  simp [logNormBot, hne x (hA_sub hx)]

/-- For a real-valued function coerced to `WithBot ℝ`, the `WithBot` ball average is the ordinary
ball average, coerced to `WithBot ℝ`. -/
lemma ballAverageWithBot_coe (u : E → ℝ) (x : E) (r : ℝ) :
    ballAverageWithBot (fun y => (u y : WithBot ℝ)) x r =
      ((ballAverage (F := ℝ) u x r : ℝ) : WithBot ℝ) := by
  simp [ballAverageWithBot, ballAverage, withBotIntegral_coe, smul_eq_mul]

/-- A positive constant can be pulled through the auxiliary real representative of a
`WithBot ℝ` value. -/
lemma unbotD_const_mul_of_pos {p : ℝ} (hp : 0 < p) (x : WithBot ℝ) :
    (WithBot.unbotD 0) ((p : WithBot ℝ) * x) = p * (WithBot.unbotD 0) x := by
  cases x with
  | bot =>
      have hp_ne : (p : WithBot ℝ) ≠ 0 := by exact_mod_cast hp.ne'
      simp [WithBot.unbotD, WithBot.mul_bot hp_ne]
  | coe a =>
      simp [WithBot.unbotD, ← WithBot.coe_mul]

/-- The auxiliary real representative of a sum is pointwise bounded by the sum of the norms of
the two auxiliary representatives. -/
lemma norm_unbotD_add_le (x y : WithBot ℝ) :
    ‖(WithBot.unbotD 0) (x + y)‖ ≤ ‖(WithBot.unbotD 0) x‖ + ‖(WithBot.unbotD 0) y‖ := by
  cases x with
  | bot => simp [WithBot.unbotD]
  | coe a =>
      cases y with
      | bot => simp [WithBot.unbotD]
      | coe b =>
          simpa [WithBot.unbotD, ← WithBot.coe_add] using norm_add_le a b

/-- For a positive constant, the `⊥` set of `p * u` is the `⊥` set of `u`. -/
lemma const_mul_eq_bot_iff_of_pos {p : ℝ} (hp : 0 < p) (x : WithBot ℝ) :
    (p : WithBot ℝ) * x = ⊥ ↔ x = ⊥ := by
  cases x with
  | bot =>
      have hp_ne : (p : WithBot ℝ) ≠ 0 := by exact_mod_cast hp.ne'
      simp [WithBot.mul_bot hp_ne]
  | coe a =>
      rw [WithBot.mul_eq_bot_iff]
      simp

/-- Positive constant multiplication is monotone on `WithBot ℝ`. -/
lemma WithBot.const_mul_le_const_mul_of_pos {p : ℝ} (hp : 0 < p)
    {x y : WithBot ℝ} (hxy : x ≤ y) :
    (p : WithBot ℝ) * x ≤ (p : WithBot ℝ) * y := by
  cases x with
  | bot =>
      have hp_ne : (p : WithBot ℝ) ≠ 0 := by exact_mod_cast hp.ne'
      cases y <;> simp [WithBot.mul_bot hp_ne]
  | coe a =>
      cases y with
      | bot =>
          simp at hxy
      | coe b =>
          exact WithBot.coe_le_coe.mpr
            (mul_le_mul_of_nonneg_left (WithBot.coe_le_coe.mp hxy) hp.le)

/-- Positive constant multiplication commutes with the `WithBot` integral. -/
lemma withBotIntegral_const_mul_of_pos {p : ℝ} (hp : 0 < p)
    (u : E → WithBot ℝ) (A : Set E) (μ : Measure E := volume) :
    withBotIntegral (fun x => (p : WithBot ℝ) * u x) A μ =
      (p : WithBot ℝ) * withBotIntegral u A μ := by
  unfold withBotIntegral
  simp_rw [const_mul_eq_bot_iff_of_pos hp]
  by_cases hbot : μ (A ∩ {x | u x = ⊥}) = 0
  · simp [hbot, unbotD_const_mul_of_pos hp, integral_const_mul]
  · simp [hbot]
    have hp_ne : (p : WithBot ℝ) ≠ 0 := by exact_mod_cast hp.ne'
    simp [WithBot.mul_bot hp_ne]

/-- Positive constant multiplication commutes with `ballAverageWithBot`. -/
lemma ballAverageWithBot_const_mul_of_pos {p : ℝ} (hp : 0 < p)
    (u : E → WithBot ℝ) (x : E) (r : ℝ) :
    ballAverageWithBot (fun y => (p : WithBot ℝ) * u y) x r =
      (p : WithBot ℝ) * ballAverageWithBot u x r := by
  unfold ballAverageWithBot
  rw [withBotIntegral_const_mul_of_pos hp]
  let q : ℝ := ((volume (ball x r)).toReal)⁻¹
  calc
    (q : WithBot ℝ) * ((p : WithBot ℝ) * ∫ᴮ (y : E) in ball x r, u y) =
        ((q : WithBot ℝ) * (p : WithBot ℝ)) *
          ∫ᴮ (y : E) in ball x r, u y := by
          rw [mul_assoc]
    _ = ((p : WithBot ℝ) * (q : WithBot ℝ)) *
          ∫ᴮ (y : E) in ball x r, u y := by
          rw [mul_comm (q : WithBot ℝ) (p : WithBot ℝ)]
    _ = (p : WithBot ℝ) *
        ((q : WithBot ℝ) * ∫ᴮ (y : E) in ball x r, u y) := by
          rw [mul_assoc]

/-- The `WithBot` ball average of the zero function is zero. -/
lemma ballAverageWithBot_zero (x : E) (r : ℝ) :
    ballAverageWithBot 0 x r = 0 := by
  simpa [ballAverage] using ballAverageWithBot_coe 0 x r

lemma WithBot.coe_mul_add (q : ℝ) (x y : WithBot ℝ) :
    (q : WithBot ℝ) * (x + y) = (q : WithBot ℝ) * x + (q : WithBot ℝ) * y := by
  by_cases hq : q = 0
  · simp [hq]
  · cases x with
    | bot =>
        have hq_wb : (q : WithBot ℝ) ≠ 0 := by exact_mod_cast hq
        cases y with
        | bot => simp [WithBot.mul_bot hq_wb]
        | coe b => simp [WithBot.mul_bot hq_wb]
    | coe a =>
        have hq_wb : (q : WithBot ℝ) ≠ 0 := by exact_mod_cast hq
        cases y with
        | bot => simp [WithBot.mul_bot hq_wb]
        | coe b =>
            norm_num [← WithBot.coe_add, ← WithBot.coe_mul]
            ring


omit [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E] [BorelSpace E] in
/-- The auxiliary real representative of a sum is integrable if both representatives are integrable
and both summands are finite almost everywhere on the integration set. -/
lemma integrableOn_unbotD_add_of_bot_null {u v : E → WithBot ℝ} {A : Set E}
    {μ : Measure E} (hA : MeasurableSet A)
    (hu_bot : μ (A ∩ {x | u x = ⊥}) = 0)
    (hv_bot : μ (A ∩ {x | v x = ⊥}) = 0)
    (hu_int : IntegrableOn ((WithBot.unbotD 0) ∘ u) A μ)
    (hv_int : IntegrableOn ((WithBot.unbotD 0) ∘ v) A μ) :
    IntegrableOn ((WithBot.unbotD 0) ∘ (u + v)) A μ := by
  refine (hu_int.add hv_int).congr_fun_ae ?_
  have hu_ne : ∀ᵐ x ∂μ.restrict A, u x ≠ ⊥ := by
    rw [ae_iff, Measure.restrict_apply_eq_zero' hA]
    simpa [inter_comm] using hu_bot
  have hv_ne : ∀ᵐ x ∂μ.restrict A, v x ≠ ⊥ := by
    rw [ae_iff, Measure.restrict_apply_eq_zero' hA]
    simpa [inter_comm] using hv_bot
  filter_upwards [hu_ne, hv_ne] with x hux hvx
  cases hux' : u x with
  | bot => exact False.elim (hux hux')
  | coe a =>
      cases hvx' : v x with
      | bot => exact False.elim (hvx hvx')
      | coe b =>
          simp [Function.comp_def, WithBot.unbotD, hux', hvx', ← WithBot.coe_add]

/-- Linearity of the `WithBot` integral under addition.  If either summand is `⊥` on a set of
positive measure, both sides reduce to `⊥`; otherwise this is ordinary Bochner integral
linearity for the real representatives. -/
lemma withBotIntegral_add {u v : E → WithBot ℝ} {A : Set E} {μ : Measure E}
    (hA : MeasurableSet A)
    (hu_int : IntegrableOn ((WithBot.unbotD 0) ∘ u) A μ)
    (hv_int : IntegrableOn ((WithBot.unbotD 0) ∘ v) A μ) :
    (∫ᴮ x in A, u x + v x ∂μ) =
      (∫ᴮ x in A, u x ∂μ) + (∫ᴮ x in A, v x ∂μ) := by
  unfold withBotIntegral
  have hsum_bot_of
      (hu_bot : μ (A ∩ {x | u x = ⊥}) = 0)
      (hv_bot : μ (A ∩ {x | v x = ⊥}) = 0) :
      μ (A ∩ {x | u x + v x = ⊥}) = 0 := by
    refine measure_mono_null ?_ (measure_union_null hu_bot hv_bot)
    intro x hx
    rcases hx with ⟨hxA, hxbot⟩
    have hxbot' : u x + v x = ⊥ := hxbot
    rw [WithBot.add_eq_bot] at hxbot'
    rcases hxbot' with hux | hvx
    · exact Or.inl ⟨hxA, hux⟩
    · exact Or.inr ⟨hxA, hvx⟩
  by_cases hu_bot : μ (A ∩ {x | u x = ⊥}) = 0
  · by_cases hv_bot : μ (A ∩ {x | v x = ⊥}) = 0
    · have hsum_bot := hsum_bot_of hu_bot hv_bot
      simp only [hsum_bot, hu_bot, hv_bot, ↓reduceIte]
      have hu_ne : ∀ᵐ x ∂μ.restrict A, u x ≠ ⊥ := by
        rw [ae_iff, Measure.restrict_apply_eq_zero' hA]
        simpa [inter_comm] using hu_bot
      have hv_ne : ∀ᵐ x ∂μ.restrict A, v x ≠ ⊥ := by
        rw [ae_iff, Measure.restrict_apply_eq_zero' hA]
        simpa [inter_comm] using hv_bot
      have h_eq :
          (fun x => (WithBot.unbotD 0) (u x + v x)) =ᵐ[μ.restrict A]
            fun x => (WithBot.unbotD 0) (u x) + (WithBot.unbotD 0) (v x) := by
        filter_upwards [hu_ne, hv_ne] with x hux hvx
        cases hux' : u x with
        | bot => exact False.elim (hux hux')
        | coe a =>
            cases hvx' : v x with
            | bot => exact False.elim (hvx hvx')
            | coe b =>
                simp [WithBot.unbotD, ← WithBot.coe_add]
      have hu_int' : IntegrableOn (fun x => (WithBot.unbotD 0) (u x)) A μ := by
        simpa [Function.comp_def] using hu_int
      have hv_int' : IntegrableOn (fun x => (WithBot.unbotD 0) (v x)) A μ := by
        simpa [Function.comp_def] using hv_int
      calc
        ((∫ x in A, (u x + v x).unbotD 0 ∂μ : ℝ) : WithBot ℝ)
            = ((∫ x in A, (u x).unbotD 0 + (v x).unbotD 0 ∂μ : ℝ) :
                WithBot ℝ) := by
                exact congrArg ((↑) : ℝ → WithBot ℝ) (integral_congr_ae h_eq)
        _ = (((∫ x in A, (u x).unbotD 0 ∂μ) +
              (∫ x in A, (v x).unbotD 0 ∂μ) : ℝ) : WithBot ℝ) := by
                rw [integral_add hu_int' hv_int']
        _ = ((∫ x in A, (u x).unbotD 0 ∂μ : ℝ) : WithBot ℝ) +
              ((∫ x in A, (v x).unbotD 0 ∂μ : ℝ) : WithBot ℝ) := by
                simp [← WithBot.coe_add]
    · have hsum_ne : μ (A ∩ {x | u x + v x = ⊥}) ≠ 0 := by
        intro hsum_bot
        exact hv_bot (measure_mono_null
          (fun x (hx : x ∈ A ∩ {x | v x = ⊥}) =>
            show x ∈ A ∩ {x | u x + v x = ⊥} from
              ⟨hx.1, by change u x + v x = ⊥; rw [WithBot.add_eq_bot]; exact Or.inr hx.2⟩)
          hsum_bot)
      have hsum_or_ne : μ (A ∩ {x | u x = ⊥ ∨ v x = ⊥}) ≠ 0 := by
        intro hsum_bot
        exact hv_bot (measure_mono_null
          (fun x (hx : x ∈ A ∩ {x | v x = ⊥}) =>
            show x ∈ A ∩ {x | u x = ⊥ ∨ v x = ⊥} from ⟨hx.1, Or.inr hx.2⟩)
          hsum_bot)
      simp [hu_bot, hv_bot, WithBot.add_eq_bot, hsum_or_ne]
  · have hsum_ne : μ (A ∩ {x | u x + v x = ⊥}) ≠ 0 := by
      intro hsum_bot
      exact hu_bot (measure_mono_null
        (fun x (hx : x ∈ A ∩ {x | u x = ⊥}) =>
          show x ∈ A ∩ {x | u x + v x = ⊥} from
            ⟨hx.1, by change u x + v x = ⊥; rw [WithBot.add_eq_bot]; exact Or.inl hx.2⟩)
        hsum_bot)
    have hsum_or_ne : μ (A ∩ {x | u x = ⊥ ∨ v x = ⊥}) ≠ 0 := by
      intro hsum_bot
      exact hu_bot (measure_mono_null
        (fun x (hx : x ∈ A ∩ {x | u x = ⊥}) =>
          show x ∈ A ∩ {x | u x = ⊥ ∨ v x = ⊥} from ⟨hx.1, Or.inl hx.2⟩)
        hsum_bot)
    simp [hu_bot, WithBot.add_eq_bot, hsum_or_ne]

/-- Linearity of `ballAverageWithBot` under addition. -/
lemma ballAverageWithBot_add {u v : E → WithBot ℝ} (x : E) (r : ℝ)
    (hu_int : IntegrableOn ((WithBot.unbotD 0) ∘ u) (ball x r))
    (hv_int : IntegrableOn ((WithBot.unbotD 0) ∘ v) (ball x r)) :
    ballAverageWithBot (fun y => u y + v y) x r =
      ballAverageWithBot u x r + ballAverageWithBot v x r := by
  unfold ballAverageWithBot
  rw [withBotIntegral_add measurableSet_ball hu_int hv_int]
  rw [WithBot.coe_mul_add]

/-- `withBotIntegral` is monotone: a pointwise `≤` implies the `WithBot`-integrals compare.
The key cases are:
· if `{u = ⊥}` has positive measure, `withBotIntegral u = ⊥ ≤ anything`;
· otherwise both are real and the comparison is the standard integral monotonicity
  (which requires integrability of the real representatives). -/
lemma withBotIntegral_mono {u v : E → WithBot ℝ} {A : Set E} {μ : Measure E}
    (hA : NullMeasurableSet A μ)
    (h : ∀ x ∈ A, u x ≤ v x)
    (hu_int : IntegrableOn (fun x => (WithBot.unbotD 0) (u x)) A μ)
    (hv_int : IntegrableOn (fun x => (WithBot.unbotD 0) (v x)) A μ) :
    withBotIntegral u A μ ≤ withBotIntegral v A μ := by
  unfold withBotIntegral
  have hsubset : A ∩ {x | v x = ⊥} ⊆ A ∩ {x | u x = ⊥} := fun x ⟨hxA, hvx⟩ =>
    ⟨hxA, le_antisymm (hvx ▸ h x hxA) bot_le⟩
  by_cases hu_bot : μ (A ∩ {x | u x = ⊥}) = 0
  · have hv_bot : μ (A ∩ {x | v x = ⊥}) = 0 := measure_mono_null hsubset hu_bot
    simp only [hu_bot, hv_bot, ↓reduceIte]
    apply WithBot.coe_le_coe.mpr
    apply setIntegral_mono_ae_restrict hu_int hv_int
    have hu_ne_bot : ∀ᵐ x ∂μ.restrict A, u x ≠ ⊥ := by
      rw [ae_iff]
      rw [Measure.restrict_apply₀' hA]
      simpa [inter_comm]
    filter_upwards [ae_restrict_mem₀ hA, hu_ne_bot] with x hxA hux_ne
    have hvx_ne : v x ≠ ⊥ := fun hvx => hux_ne (le_antisymm (hvx ▸ h x hxA) bot_le)
    cases hux : u x with
    | bot => exact False.elim (hux_ne hux)
    | coe a =>
      cases hvx : v x with
      | bot => exact False.elim (hvx_ne hvx)
      | coe b =>
        exact WithBot.coe_le_coe.mp (by simpa [hux, hvx] using h x hxA)
  · simp [hu_bot]

/-- `ballAverageWithBot` is monotone in the integrand (pointwise inequality → average inequality),
provided the real representatives of both functions are integrable on the ball. -/
lemma ballAverageWithBot_mono {u v : E → WithBot ℝ} {x : E} {r : ℝ}
    (h : ∀ y, u y ≤ v y)
    (hu_int : IntegrableOn (fun y => (WithBot.unbotD 0) (u y)) (ball x r))
    (hv_int : IntegrableOn (fun y => (WithBot.unbotD 0) (v y)) (ball x r)) :
    ballAverageWithBot u x r ≤ ballAverageWithBot v x r := by
  unfold ballAverageWithBot
  by_cases hc : ((volume (ball x r)).toReal)⁻¹ = 0
  · simp [hc]
  · have hc_pos : 0 < ((volume (ball x r)).toReal)⁻¹ :=
      lt_of_le_of_ne (inv_nonneg.mpr ENNReal.toReal_nonneg) (Ne.symm hc)
    exact WithBot.const_mul_le_const_mul_of_pos hc_pos
      (withBotIntegral_mono isOpen_ball.nullMeasurableSet (fun y hy => h y) hu_int hv_int)

-- # Here's the defintion of `subharmonic functions`:
/-- A function is subharmonic on a set if it is upper semicontinuous, locally integrable in the
`WithBot` sense, and satisfies the local sub-mean inequality on sufficiently small balls. -/
def SubharmonicOn (u : E → WithBot ℝ) (s : Set E) : Prop :=
  UpperSemicontinuousOn u s ∧
    ∀ x ∈ s, ∃ ρ > 0, ball x ρ ⊆ s ∧
      ∀ r, 0 < r ∧ r < ρ → u x ≤ ballAverageWithBot u x r


/-- The `⊥` set of an upper semicontinuous `WithBot ℝ`-valued function is null-measurable on
every ball contained in the domain. -/
lemma UpperSemicontinuousOn.nullMeasurableSet_eq_bot_ball
    (husc : UpperSemicontinuousOn u s) {x : E} {ρ : ℝ} (hball : ball x ρ ⊆ s) :
    NullMeasurableSet (ball x ρ ∩ {y | u y = ⊥}) volume := by
  have hball_usc : UpperSemicontinuousOn u (ball x ρ) := husc.mono hball
  have hpre :=
    (upperSemicontinuousOn_iff_preimage_Iio (f := u) (s := ball x ρ)).1 hball_usc
  have hlevel :
      ∀ n : ℕ,
        MeasurableSet
          (ball x ρ ∩ {y | u y < (((-(n : ℝ)) : ℝ) : WithBot ℝ)}) := by
    intro n
    rcases hpre (((-(n : ℝ)) : ℝ) : WithBot ℝ) with ⟨U, hU_open, hU_eq⟩
    change MeasurableSet (ball x ρ ∩ u ⁻¹' Iio (((-(n : ℝ)) : ℝ) : WithBot ℝ))
    rw [hU_eq]
    exact measurableSet_ball.inter hU_open.measurableSet
  have h_eq :
      ball x ρ ∩ {y | u y = ⊥} =
        ⋂ n : ℕ, ball x ρ ∩ {y | u y < (((-(n : ℝ)) : ℝ) : WithBot ℝ)} := by
    ext y
    constructor
    · intro hy
      rcases hy with ⟨hy_ball, hy_bot⟩
      rw [mem_iInter]
      intro n
      have hlt : (⊥ : WithBot ℝ) < (((-(n : ℝ)) : ℝ) : WithBot ℝ) := by simp
      have hy_bot' : u y = ⊥ := by simpa using hy_bot
      exact ⟨hy_ball, by change u y < (((-(n : ℝ)) : ℝ) : WithBot ℝ); rw [hy_bot']; exact hlt⟩
    · intro hy
      have hy_ball : y ∈ ball x ρ := (mem_iInter.mp hy 0).1
      refine ⟨hy_ball, ?_⟩
      cases huy : u y with
      | bot => exact huy
      | coe a =>
          have hall : ∀ n : ℕ, a < -(n : ℝ) := by
            intro n
            have hn := (mem_iInter.mp hy n).2
            have hn' : u y < (((-(n : ℝ)) : ℝ) : WithBot ℝ) := by simpa using hn
            simpa [huy] using hn'
          obtain ⟨n, hn⟩ := exists_nat_ge (-a)
          have hle : -(n : ℝ) ≤ a := by linarith
          exact False.elim ((not_lt_of_ge hle) (hall n))
  rw [h_eq]
  exact (MeasurableSet.iInter hlevel).nullMeasurableSet


/-- Restrict a subharmonic function to an open subset. -/
lemma SubharmonicOn.mono (hu : SubharmonicOn u s) {t : Set E}
    (hts : t ⊆ s) (ht : IsOpen t) : SubharmonicOn u t := by
  constructor
  · exact hu.1.mono hts
  · intro x hx
    rcases hu.2 x (hts hx) with ⟨ρs, hρs_pos, _hρs_sub, hmean⟩
    rcases Metric.isOpen_iff.mp ht x hx with ⟨ρt, hρt_pos, hρt_sub⟩
    refine ⟨min ρs ρt, lt_min hρs_pos hρt_pos, ?_, ?_⟩
    · intro y hy
      exact hρt_sub (Metric.ball_subset_ball (min_le_right _ _) hy)
    · intro r hr
      exact hmean r ⟨hr.1, lt_of_lt_of_le hr.2 (min_le_left _ _)⟩

/-- The sum of two subharmonic `WithBot ℝ`-valued functions is subharmonic.  This is the
convex-cone addition property; the mean-value part is the usual addition of the two sub-mean
inequalities, with the `⊥` cases handled by `withBotIntegral`. -/
theorem SubharmonicOn.add (hu : SubharmonicOn u s) {v : E → WithBot ℝ}
    (hv : SubharmonicOn v s) : SubharmonicOn (u + v) s := by
  constructor
  · exact hu.1.withBot_add hv.1
  · intro x hx
    rcases hu.2 x hx with ⟨ρu, hρu_pos, hρu_sub, hmean_u⟩
    rcases hv.2 x hx with ⟨ρv, hρv_pos, hρv_sub, hmean_v⟩
    refine ⟨min ρu ρv, lt_min hρu_pos hρv_pos, ?_, ?_⟩
    · intro y hy
      exact hρu_sub (Metric.ball_subset_ball (min_le_left _ _) hy)
    · intro r hr
      -- This is the mean-value additivity step.  It should use `ballAverageWithBot_add`
      -- once the needed local integrability bookkeeping is supplied.
      sorry





/-- Every real-valued harmonic function on an open set is subharmonic for the local
sub-mean definition. -/
theorem harmonicOnNhd_subharmonicOn
  [Nontrivial E] (u : E → ℝ) (s : Set E) (hs : IsOpen s)
  (hu : InnerProductSpace.HarmonicOnNhd u s) :
  SubharmonicOn (fun z => (u z : WithBot ℝ)) s := by
  constructor
  · exact (hu.continuousOn.upperSemicontinuousOn).withBot_coe
  · intro x hx
    rcases Metric.isOpen_iff.mp hs x hx with ⟨ρ, hρ_pos, hρ_sub⟩
    refine ⟨ρ / 2, half_pos hρ_pos, ?_, ?_⟩
    · intro y hy
      exact hρ_sub (Metric.ball_subset_ball (by linarith) hy)
    · intro r hr
      have hclosed_sub : closedBall x |r| ⊆ s := by
        intro y hy
        exact hρ_sub (by
          rw [Metric.mem_ball]
          exact lt_of_le_of_lt (by simpa [Metric.mem_closedBall] using hy)
            (by rw [abs_of_pos hr.1]; linarith))
      rw [ballAverageWithBot_coe]
      refine WithBot.coe_le_coe.mpr ?_
      have hmean : ballAverage u x r = u x := by
        simpa [abs_of_pos hr.1] using
          HarmonicOnNhd.ballAverage_eq
            ((hu.mono hclosed_sub) : InnerProductSpace.HarmonicOnNhd u (closedBall x |r|))
      exact le_of_eq hmean.symm

/-- Subtracting a harmonic real-valued function from a subharmonic `WithBot ℝ`-valued function
preserves subharmonicity on any open subset where the harmonic function is defined. -/
lemma SubharmonicOn.sub_harmonicOnNhd [Nontrivial E] (hu : SubharmonicOn u s)
    {t : Set E} (hts : t ⊆ s) (ht : IsOpen t) {h : E → ℝ}
    (hharm : InnerProductSpace.HarmonicOnNhd h t) :
    SubharmonicOn (fun z => u z + ((-h z : ℝ) : WithBot ℝ)) t := by
  have hu_t : SubharmonicOn u t := hu.mono hts ht
  have hneg_harm : InnerProductSpace.HarmonicOnNhd (fun z => -h z) t := by
    simpa using hharm.neg
  have hneg_sub : SubharmonicOn (fun z => ((-h z : ℝ) : WithBot ℝ)) t :=
    harmonicOnNhd_subharmonicOn (fun z => -h z) t ht hneg_harm
  exact hu_t.add hneg_sub

/-- Maximum-principle form of the local sub-mean property on a ball: if a subharmonic function is
nonpositive on the boundary sphere, then it is nonpositive throughout the open ball. -/
lemma SubharmonicOn.maximum_principle_on_ball [Nontrivial E] (hu : SubharmonicOn u s)
    (hs : IsOpen s) {x : E} {r M : ℝ}
    (hball : ball x r ⊆ s) (hbd : ∀ y ∈ sphere x r, u y ≤ M) :
    ∀ y ∈ ball x r, u y ≤ M := by
  sorry

/-- The local sub-mean definition implies the harmonic comparison principle on balls:
if a harmonic function dominates a subharmonic function on the boundary, then it dominates it
inside. -/
theorem SubharmonicOn.harmonicComparison [Nontrivial E] (hu : SubharmonicOn u s)
    (_hs : IsOpen s) :
    ∀ (x : E) (r : ℝ) (h : E → ℝ),
      closedBall x r ⊆ s → ContinuousOn h (closedBall x r) →
      InnerProductSpace.HarmonicOnNhd h (ball x r) →
      (∀ y ∈ sphere x r, u y ≤ h y) → ∀ y ∈ ball x r, u y ≤ h y := by
  intro x r h hclosed _hcont hharm hbd y hy
  let v : E → WithBot ℝ := fun z => u z + ((-h z : ℝ) : WithBot ℝ)
  have hball_sub_s : ball x r ⊆ s := ball_subset_closedBall.trans hclosed
  have hv_sub : SubharmonicOn v (ball x r) :=
    hu.sub_harmonicOnNhd hball_sub_s isOpen_ball hharm
  have hv_bd : ∀ y ∈ sphere x r, v y ≤ 0 := by
    intro y hy
    exact (WithBot.add_neg_coe_le_zero_iff (u y) (h y)).2 (hbd y hy)
  have hv_y : v y ≤ 0 :=
    hv_sub.maximum_principle_on_ball isOpen_ball (Subset.refl _) hv_bd y hy
  exact (WithBot.add_neg_coe_le_zero_iff (u y) (h y)).1 hv_y




/--The extended notion of `HarmonicAt` for `WithBot ℝ`-valued function at `x`. -/
def HarmonicAtWithBot (u : E → WithBot ℝ) (x : E) : Prop :=
  ∃ v : E → ℝ, InnerProductSpace.HarmonicAt v x ∧ u =ᶠ[𝓝 x] (v ·)



/-- An upper semicontinuous function which is locally harmonic at every finite
point is subharmonic. -/
theorem subharmonicOn_of_upperSemicontinuousOn_of_harmonicAtWithBot [Nontrivial E]
    {u : E → WithBot ℝ} {s : Set E} (hs : IsOpen s) (husc : UpperSemicontinuousOn u s)
    (hu : ∀ z ∈ s, u z ≠ ⊥ → HarmonicAtWithBot u z) : SubharmonicOn u s := by
  constructor
  · exact husc
  · intro x hx
    rcases Metric.isOpen_iff.mp hs x hx with ⟨ρ₀, hρ₀_pos, hρ₀_sub⟩
    by_cases hux : u x = ⊥
    · -- u x = ⊥, so ⊥ ≤ anything
      exact ⟨ρ₀, hρ₀_pos, hρ₀_sub, fun _ _ => hux ▸ bot_le⟩
    · -- u x is finite; extract local harmonic representative
      obtain ⟨v, hv, huv⟩ := hu x hx hux
      -- Get metric ball where u = v
      obtain ⟨N_uv, hN_uv, huv_N⟩ := huv.exists_mem
      obtain ⟨ρ_uv, hρ_uv_pos, hρ_uv_sub⟩ := Metric.mem_nhds_iff.mp hN_uv
      -- Get metric ball where v is harmonic at every point
      obtain ⟨N_v, hN_v, hv_N⟩ := hv.eventually.exists_mem
      obtain ⟨ρ_v, hρ_v_pos, hρ_v_sub⟩ := Metric.mem_nhds_iff.mp hN_v
      -- Use ρ = minimum of all three radii
      refine ⟨min (min ρ₀ ρ_uv) ρ_v, lt_min (lt_min hρ₀_pos hρ_uv_pos) hρ_v_pos, ?_, ?_⟩
      · -- ball x ρ ⊆ s
        intro y hy
        exact hρ₀_sub (Metric.ball_subset_ball (le_trans (min_le_left _ _) (min_le_left _ _)) hy)
      · intro r ⟨hr_pos, hr_lt⟩
        have hr_lt_uv : r < ρ_uv :=
          lt_of_lt_of_le hr_lt (le_trans (min_le_left _ _) (min_le_right _ _))
        have hr_lt_v : r < ρ_v := lt_of_lt_of_le hr_lt (min_le_right _ _)
        -- u = v on ball x r
        have hu_eq_v_ball : ∀ y ∈ ball x r, u y = (v y : WithBot ℝ) := fun y hy =>
          huv_N (hρ_uv_sub (Metric.ball_subset_ball hr_lt_uv.le hy))
        -- u x = v x
        have hux_eq : u x = (v x : WithBot ℝ) := huv_N (mem_of_mem_nhds hN_uv)
        -- v is harmonic at every point of closedBall x r
        have hv_harm : InnerProductSpace.HarmonicOnNhd v (closedBall x r) := fun y hy =>
          hv_N y (hρ_v_sub (Metric.closedBall_subset_ball hr_lt_v hy))
        -- Mean value property: ballAverage v x r = v x
        have hmean : ballAverage v x r = v x :=
          HarmonicOnNhd.ballAverage_eq
            (show InnerProductSpace.HarmonicOnNhd v (closedBall x |r|) by rwa [abs_of_pos hr_pos])
        -- Real integrals agree on the ball since u = v there
        have hint_eq : ∫ y in ball x r, (u y).unbotD 0 = ∫ y in ball x r, v y := by
          apply setIntegral_congr_ae measurableSet_ball (ae_of_all _ _)
          intro y hy
          rw [hu_eq_v_ball y hy]
          simp [WithBot.unbotD]
        -- withBotIntegrals agree
        have h_u_bot : volume (ball x r ∩ {y | u y = ⊥}) = 0 := by
          have hempty : ball x r ∩ {y | u y = ⊥} = ∅ := by
            ext y
            simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false,
              not_and]
            intro hy_ball; rw [hu_eq_v_ball y hy_ball]; exact WithBot.coe_ne_bot
          simp [hempty, measure_empty]
        have hwbi_eq : withBotIntegral u (ball x r) =
            withBotIntegral (fun y => (v y : WithBot ℝ)) (ball x r) := by
          rw [withBotIntegral_coe]
          unfold withBotIntegral
          rw [if_pos h_u_bot, hint_eq]
        -- ballAverageWithBots agree
        have hball_avg_eq : ballAverageWithBot u x r =
            ballAverageWithBot (fun y => (v y : WithBot ℝ)) x r := by
          simp only [ballAverageWithBot, hwbi_eq]
        -- Conclude: u x = ballAverageWithBot u x r
        suffices heq : u x = ballAverageWithBot u x r from heq.le
        calc u x
            = (v x : WithBot ℝ) := hux_eq
          _ = ((ballAverage (F := ℝ) v x r : ℝ) : WithBot ℝ) := by exact_mod_cast hmean.symm
          _ = ballAverageWithBot (fun y => (v y : WithBot ℝ)) x r := (ballAverageWithBot_coe v x r).symm
          _ = ballAverageWithBot u x r := hball_avg_eq.symm


/-- A nonnegative constant multiple of a subharmonic function is subharmonic. -/
theorem SubharmonicOn.const_mul [Nontrivial E] {p : ℝ} (hp : 0 ≤ p) (hu : SubharmonicOn u s) :
  SubharmonicOn (fun z => (p : WithBot ℝ) * u z) s := by
  constructor
  · exact hu.1.const_mul hp
  · intro x hx
    rcases hu.2 x hx with ⟨ρ, hρ_pos, hρ_sub, hmean⟩
    refine ⟨ρ, hρ_pos, hρ_sub, ?_⟩
    intro r hr
    by_cases hp0 : p = 0
    · simp only [hp0, WithBot.coe_zero, zero_mul]
      exact le_of_eq (ballAverageWithBot_zero (E := E) x r).symm
    · have hp_pos : 0 < p := lt_of_le_of_ne hp (Ne.symm hp0)
      rw [ballAverageWithBot_const_mul_of_pos hp_pos]
      exact WithBot.const_mul_le_const_mul_of_pos hp_pos (hmean r hr)

/-- `expBot` is monotone on `WithBot ℝ`. -/
lemma expBot_mono {a b : WithBot ℝ} (h : a ≤ b) : expBot a ≤ expBot b := by
  cases a with
  | bot =>
    calc expBot (⊥ : WithBot ℝ) = 0 := by simp [expBot]
      _ ≤ expBot b := by cases b <;> simp [expBot, exp_nonneg]
  | coe x =>
    cases b with
    | bot => exact absurd h (not_le.mpr (WithBot.bot_lt_coe x))
    | coe y =>
      simp only [expBot_coe]
      exact Real.exp_le_exp.mpr (WithBot.coe_le_coe.mp h)

/-- Jensen's inequality for `expBot` and `ballAverageWithBot`: the exponential of the
`WithBot`-mean is at most the mean of the exponentials.

This is the mean-value ingredient needed to prove that `expBot ∘ u` is subharmonic directly from
the local sub-mean definition. -/
lemma expBot_ballAverageWithBot_le (u : ℂ → WithBot ℝ) (x : ℂ) {r : ℝ} (hr : 0 < r) :
  expBot (ballAverageWithBot u x r) ≤ ballAverageWithBot (fun z => (expBot (u z) : WithBot ℝ)) x r := sorry


/-- Applying `expBot` to a subharmonic `WithBot ℝ`-valued function preserves subharmonicity. -/
theorem SubharmonicOn.expBot_comp {u : ℂ → WithBot ℝ} {s : Set ℂ} (hu : SubharmonicOn u s) :
  SubharmonicOn (fun z => expBot (u z)) s := by
  constructor
  · exact hu.1.expBot_mul.withBot_coe
  · intro x hx
    rcases hu.2 x hx with ⟨ρ, hρ_pos, hρ_sub, hmean⟩
    exact ⟨ρ, hρ_pos, hρ_sub, fun r hr =>
      calc (expBot (u x) : WithBot ℝ)
          ≤ (expBot (ballAverageWithBot u x r) : WithBot ℝ) :=
              WithBot.coe_le_coe.mpr (expBot_mono (hmean r hr))
        _ ≤ ballAverageWithBot (fun z => (expBot (u z) : WithBot ℝ)) x r :=
              expBot_ballAverageWithBot_le u x hr.1⟩



-- # The following lemma will be useful for estimating function e.g. |f|^p
/-- A real-valued subharmonic function is bounded above by the Poisson integral of its boundary
values on a disk. -/
theorem SubharmonicOn.le_circleAverage_poissonKernel_smul
    {u : ℂ → ℝ} {s : Set ℂ} {c w : ℂ} {R : ℝ}
    (hu : SubharmonicOn (fun z => (u z : WithBot ℝ)) s)
    (hs : IsOpen s)
    (hu_cont : ContinuousOn u (sphere c R))
    (hclosed : closedBall c R ⊆ s) (hw : w ∈ ball c R) :
    u w ≤ circleAverage (fun z => poissonKernel c w z * u z) c R  := by
  rcases poissonIntegral_continuousOn_closedBall_eq_boundary
    (c := c) (R := R) hu_cont with
    ⟨h, hcont, hharm, hPoisson, hboundary⟩
  have hbd : ∀ y ∈ sphere c R, (u y : WithBot ℝ) ≤ h y := by
    intro y hy
    rw [hboundary y hy]
  have hle : (u w : WithBot ℝ) ≤ h w :=
    hu.harmonicComparison hs c R h hclosed hcont hharm hbd w hw
  have hle_real : u w ≤ h w := WithBot.coe_le_coe.mp hle
  rw [hPoisson w hw] at hle_real
  exact hle_real
-- Note actually I don't need continuity condition but the proof might be tough (using sequence
-- to approach then translate the inequality)


variable [NormedSpace ℂ E] [NormedSpace ℂ F]

/-- If `f` is analytic on an open set, then `log ‖f‖`, with value `⊥` at zeros, is upper
semicontinuous there. -/
lemma logNormBot_comp_analytic_upperSemicontinuousOn_banach [DecidableEq F]
    {f : ℂ → F} {s : Set ℂ} (_hs : IsOpen s) (hf : AnalyticOn ℂ f s) :
    UpperSemicontinuousOn (logNormBot.comp f) s := by
  intro x hx a hlt
  cases a with
  | bot => exact False.elim (not_lt_bot hlt)
  | coe c =>
      have hnorm_lt : ‖f x‖ < exp c := by
        by_cases hfx : f x = 0
        · simpa [hfx] using exp_pos c
        · apply (Real.log_lt_iff_lt_exp (norm_pos_iff.mpr hfx)).mp
          apply WithBot.coe_lt_coe.mp
          simpa [Function.comp_def, logNormBot, hfx] using hlt
      filter_upwards [(hf.continuousOn x hx).norm (Iio_mem_nhds hnorm_lt)] with y hy
      by_cases hfy : f y = 0
      · simp [logNormBot, hfy]
      · simp [logNormBot, hfy]
        exact (Real.log_lt_iff_lt_exp (norm_pos_iff.mpr hfy)).mpr hy

/-- Scalar-valued analytic functions have subharmonic logarithmic modulus. -/
theorem logNormBot_comp_analytic_subharmonicOn_scalar {f : ℂ → ℂ} {s : Set ℂ}
  (hs : IsOpen s) (hf : AnalyticOn ℂ f s) : SubharmonicOn (logNormBot ∘ f) s := by
  refine subharmonicOn_of_upperSemicontinuousOn_of_harmonicAtWithBot hs
    (logNormBot_comp_analytic_upperSemicontinuousOn_banach hs hf) ?_
  intro z hz hfinite
  have hfz_ne : f z ≠ 0 := by
    intro hfz
    exact hfinite (by simp [logNormBot, hfz])
  have hfz_an : AnalyticAt ℂ f z := hf.analyticAt (hs.mem_nhds hz)
  let v : ℂ → ℝ := fun y => log ‖f y‖
  have hvz : InnerProductSpace.HarmonicAt v z :=
    hfz_an.harmonicAt_log_norm hfz_ne
  refine ⟨v, hvz, ?_⟩
  filter_upwards [hfz_an.continuousAt.eventually_ne hfz_ne] with y hy
  simp [logNormBot, v, hy]


theorem logNormBot_comp_analytic_subharmonicOn_banach [DecidableEq F] {f : ℂ → F} {s : Set ℂ}
  (hs : IsOpen s) (hf : AnalyticOn ℂ f s) : SubharmonicOn (logNormBot ∘ f) s := by
  constructor
  · exact logNormBot_comp_analytic_upperSemicontinuousOn_banach hs hf
  · intro w hw
    by_cases hfw : f w = 0
    · rcases Metric.isOpen_iff.mp hs w hw with ⟨ρ, hρ_pos, hρ_sub⟩
      exact ⟨ρ, hρ_pos, hρ_sub, fun r _ =>
        by simp [Function.comp_def, logNormBot, hfw]⟩
    · obtain ⟨ℓ, hℓ_norm, hℓw⟩ := exists_dual_vector'' ℂ (f w)
      let g : ℂ → ℂ := ℓ ∘ f
      have hg_analytic : AnalyticOn ℂ g s := ℓ.comp_analyticOn hf
      have hg_sub : SubharmonicOn (logNormBot.comp g) s :=
        logNormBot_comp_analytic_subharmonicOn_scalar hs hg_analytic
      have hg_eq : (logNormBot.comp g) w = (logNormBot.comp f) w := by
        have hℓfw_ne : ℓ (f w) ≠ 0 := by
          rw [hℓw]
          exact Complex.ofReal_ne_zero.mpr (norm_ne_zero_iff.mpr hfw)
        simp [Function.comp_def, g, logNormBot, hfw, hℓw]
      have hpointwise : ∀ z, (logNormBot.comp g) z ≤ (logNormBot.comp f) z := by
        intro z
        have hlog_le : logNormBot (ℓ (f z)) ≤ logNormBot (f z) := by
          by_cases hℓz : ℓ (f z) = 0
          · simp [logNormBot, hℓz]
          · have hfz : f z ≠ 0 := by
              intro hfz
              exact hℓz (by simp [hfz])
            have hnorm_le : ‖ℓ (f z)‖ ≤ ‖f z‖ := by
              grw [ℓ.le_opNorm (f z), hℓ_norm]
              simp
            simp [logNormBot, hℓz, hfz]
            exact Real.log_le_log (norm_pos_iff.mpr hℓz) hnorm_le
        exact hlog_le
      have hgw_ne : g w ≠ 0 := by
        rw [show g w = ℓ (f w) by rfl, hℓw]
        exact Complex.ofReal_ne_zero.mpr (norm_ne_zero_iff.mpr hfw)
      rcases hg_sub.2 w hw with ⟨ρ₀, hρ₀_pos, hρ₀_sub, hg_mean⟩
      rcases Metric.eventually_nhds_iff.mp
          ((hf.analyticAt (hs.mem_nhds hw)).continuousAt.eventually_ne hfw) with
        ⟨ρf, hρf_pos, hρf_ne⟩
      rcases Metric.eventually_nhds_iff.mp
          ((hg_analytic.analyticAt (hs.mem_nhds hw)).continuousAt.eventually_ne hgw_ne) with
        ⟨ρg, hρg_pos, hρg_ne⟩
      refine ⟨min (min ρ₀ ρf) ρg, lt_min (lt_min hρ₀_pos hρf_pos) hρg_pos, ?_, fun r hr => ?_⟩
      · intro y hy
        exact hρ₀_sub (Metric.ball_subset_ball
          (le_trans (min_le_left _ _) (min_le_left _ _)) hy)
      have hr_lt_ρ₀ : r < ρ₀ :=
        lt_of_lt_of_le hr.2 (le_trans (min_le_left _ _) (min_le_left _ _))
      have hr_lt_ρf : r < ρf :=
        lt_of_lt_of_le hr.2 (le_trans (min_le_left _ _) (min_le_right _ _))
      have hr_lt_ρg : r < ρg :=
        lt_of_lt_of_le hr.2 (min_le_right _ _)
      have hclosed_sub_s : closedBall w r ⊆ s := fun y hy =>
        hρ₀_sub (Metric.closedBall_subset_ball hr_lt_ρ₀ hy)
      have hf_ne_closed : ∀ y ∈ closedBall w r, f y ≠ 0 := by
        intro y hy
        exact hρf_ne (lt_of_le_of_lt (by simpa [dist_comm, Metric.mem_closedBall] using hy) hr_lt_ρf)
      have hg_ne_closed : ∀ y ∈ closedBall w r, g y ≠ 0 := by
        intro y hy
        exact hρg_ne (lt_of_le_of_lt (by simpa [dist_comm, Metric.mem_closedBall] using hy) hr_lt_ρg)
      have hg_int : IntegrableOn ((WithBot.unbotD 0) ∘ logNormBot ∘ g) (ball w r) := by
        exact integrableOn_unbotD_logNormBot_comp_of_continuousOn_of_ne_on
          (f := g) (A := ball w r) (K := closedBall w r) (μ := volume)
          (hg_analytic.continuousOn.mono hclosed_sub_s) (isCompact_closedBall w r)
          measurableSet_ball ball_subset_closedBall measure_ball_lt_top.ne hg_ne_closed
      have hf_int : IntegrableOn ((WithBot.unbotD 0) ∘ logNormBot ∘ f) (ball w r) := by
        exact integrableOn_unbotD_logNormBot_comp_of_continuousOn_of_ne_on
          (f := f) (A := ball w r) (K := closedBall w r) (μ := volume)
          (hf.continuousOn.mono hclosed_sub_s) (isCompact_closedBall w r)
          measurableSet_ball ball_subset_closedBall measure_ball_lt_top.ne hf_ne_closed
      have hf_bot : volume (ball w r ∩ {y | (logNormBot ∘ f) y = ⊥}) = 0 := by
        have hempty : ball w r ∩ {y | (logNormBot ∘ f) y = ⊥} = ∅ := by
          ext y
          simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false,
            not_and]
          intro hy_ball
          have hy_closed : y ∈ closedBall w r := ball_subset_closedBall hy_ball
          simp [logNormBot, hf_ne_closed y hy_closed]
        rw [hempty]; simp
      grw [hg_eq.symm, hg_mean r ⟨hr.1, hr_lt_ρ₀⟩, ballAverageWithBot_mono hpointwise hg_int hf_int]

theorem norm_rpow_comp_analytic_subharmonicOn_banach [DecidableEq F] {f : ℂ → F} {p : ℝ} {s : Set ℂ}
  (hs : IsOpen s) (hf : AnalyticOn ℂ f s) (hp : 0 < p) :
  SubharmonicOn (fun z => ((‖f z‖ ^ p : ℝ) : WithBot ℝ)) s := by
  simpa [Function.comp_def, exp_mul_logNorm_eq_norm_rpow hp] using
    ((logNormBot_comp_analytic_subharmonicOn_banach hs hf).const_mul hp.le).expBot_comp


end
